In [1]:
import selenium
from selenium import webdriver
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import time

# Buitiful soup if needed
from bs4 import BeautifulSoup
#Importing requests
import requests
# importing regex
import re

#importing exceptions error
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException


from selenium.webdriver.common.keys import Keys

In [2]:
driver=webdriver.Chrome(r'C:\Users\surendar.reddy\Documents\data Science projet_Data traine\chromedriver.exe')
time.sleep(3)

In [3]:
url = "https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=BOM&destinationCountry=IN&flight_depart_date=26%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-flights&unqvaldesktop=1206718911299"
driver.get(url)

In [4]:
clear_ITEM1=driver.find_element_by_id("origin_0").clear()
time.sleep(2)
clear_ITEM2=driver.find_element_by_id("destination_0").clear()
time.sleep(2)

start_ITEM=driver.find_element_by_id("origin_0")
end_ITEM=driver.find_element_by_id("destination_0")
a=input(str("Enter ITEM start NAME: "))
b=input(str("Enter ITEM End NAME: "))
start_ITEM.send_keys(a)
time.sleep(10)
end_ITEM.send_keys(b)

time.sleep(5)
select_flight=driver.find_element_by_xpath('//button[@class="fs-14 btn-submit cursor-pointer bold"]').click()


#ng-class="modifySearch.$valid== false || submitted ||specialFareError.error?'disabled   ':''"
#class="fs-16 bold ng-touched ng-dirty ng-valid-parse ng-invalid ng-invalid-required ellipsis full-width ng-pristine ng-valid ng-not-empty ng-valid-required"

Enter ITEM start NAME: Hyderabad
Enter ITEM End NAME: Mumbai

In [18]:
HYD_MUM_26apr = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     HYD_MUM_26apr.append(i.text.split('\n'))
HYD_MUM_26apr

[['DEALBook this flight and get upto Rs. 1,500 OFF. Use code: FLYNOW',
  'Vistara',
  'UK-878',
  '12:55',
  'Hyderabad',
  '14:30',
  'Mumbai',
  '1h 35m',
  'Non Stop',
  '1 left at5,528',
  'Book Now',
  'Flight Details',
  'Free Meal',
  'Emissions: 169 Kg CO2',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,900 OFF. Use code: FLYNOW',
  'IndiGo',
  '6E-5316',
  '21:45',
  'Hyderabad',
  '23:10',
  'Mumbai',
  '1h 25m',
  'Non Stop',
  '4 left at6,105',
  'View Fares',
  'Flight Details',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,500 OFF. Use code: FLYNOW',
  'Vistara',
  'UK-876',
  '21:35',
  'Hyderabad',
  '23:00',
  'Mumbai',
  '1h 25m',
  'Non Stop',
  '1 left at6,263',
  'Book Now',
  'Flight Details',
  'Free Meal',
  'Emissions: 169 Kg CO2',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,900 OFF. Use code: FLYNOW',
  'IndiGo',
  '6E-6699',
  '13:15',
  'Hyderabad',
  '14:45',
  'Mumbai',
  '1h 30m',
  'Non Stop',
  '4 left at6,315',
  'View Fares',
  'Flight Details',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,800 OFF. Use code: FLYNOW',
  'Air Asia',
  'I5-972/472',
  '16:35',
  'Hyderabad',
  '23:45',
  'Mumbai',
  '7h 10m',
  '1 Stop',
  '6,655',
  'View Fares',
  'Flight Details',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,800 OFF. Use code: FLYNOW',
  'Air Asia',
  'I5-974/334',
  '20:20',
  'Hyderabad',
  '00:20',
  '+ 1 day',
  'Mumbai',
  '4h 00m',
  '1 Stop',
  '7,522',
  'View Fares',
  'Flight Details',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,800 OFF. Use code: FLYNOW',
  'Air Asia',
  'I5-1543/334',
  '14:20',
  'Hyderabad',
  '00:20',
  '+ 1 day',
  'Mumbai',
  '10h 00m',
  '1 Stop',
  '7,522',
  'View Fares',
  'Flight Details',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,900 OFF. Use code: FLYNOW',
  'IndiGo',
  '6E-5389',
  '19:15',
  'Hyderabad',
  '20:35',
  'Mumbai',
  '1h 20m',
  'Non Stop',
  '2 left at7,785',
  'View Fares',
  'Flight Details',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,350 OFF. Use code: FLYNOW',
  'Air India',
  'AI-840/887',
  '20:40',
  'Hyderabad',
  '09:05',
  '+ 1 day',
  'Mumbai',
  '12h 25m',
  '1 Stop',
  '8,009',
  'Book Now',
  'Flight Details',
  'Free Meal',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,350 OFF. Use code: FLYNOW',
  'Air India',
  'AI-840/665',
  '20:40',
  'Hyderabad',
  '10:10',
  '+ 1 day',
  'Mumbai',
  '13h 30m',
  '1 Stop',
  '8,009',
  'Book Now',
  'Flight Details',
  'Free Meal',
  'Emissions: 652 Kg CO2',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,350 OFF. Use code: FLYNOW',
  'Air India',
  'AI-840/865',
  '20:40',
  'Hyderabad',
  '12:35',
  '+ 1 day',
  'Mumbai',
  '15h 55m',
  '1 Stop',
  '8,009',
  'Book Now',
  'Flight Details',
  'Free Meal',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,350 OFF. Use code: FLYNOW',
  'Air India',
  'AI-840/863',
  '20:40',
  'Hyderabad',
  '16:15',
  '+ 1 day',
  'Mumbai',
  '19h 35m',
  '1 Stop',
  '8,009',
  'Book Now',
  'Flight Details',
  'Free Meal',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,350 OFF. Use code: FLYNOW',
  'Air India',
  'AI-840/624',
  '20:40',
  'Hyderabad',
  '21:15',
  '+ 1 day',
  'Mumbai',
  '24h 35m',
  '1 Stop',
  '8,009',
  'Book Now',
  'Flight Details',
  'Free Meal',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,350 OFF. Use code: FLYNOW',
  'Air India',
  'AI-840/441',
  '20:40',
  'Hyderabad',
  '21:35',
  '+ 1 day',
  'Mumbai',
  '24h 55m',
  '2 Stop(s)',
  '8,009',
  'Book Now',
  'Flight Details',
  'Free Meal',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,500 OFF. Use code: FLYNOW',
  'SpiceJet',
  'SG-3736/454',
  '19:10',
  'Hyderabad',
  '14:55',
  '+ 1 day',
  'Mumbai',
  '19h 45m',
  '1 Stop',
  '8,751',
  'View Fares',
  'Flight Details',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,350 OFF. Use code: FLYNOW',
  'Air India',
  'AI-840/636',
  '20:40',
  'Hyderabad',
  '18:10',
  '+ 1 day',
  'Mumbai',
  '21h 30m',
  '2 Stop(s)',
  '8,933',
  'Book Now',
  'Flight Details',
  'Free Meal',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,900 OFF. Use code: FLYNOW',
  'IndiGo',
  '6E-6433/5248',
  '21:40',
  'Hyderabad',
  '01:30',
  '+ 1 day',
  'Mumbai',
  '3h 50m',
  '1 Stop',
  '9,622',
  'View Fares',
  'Flight Details',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,900 OFF. Use code: FLYNOW',
  'IndiGo',
  '6E-309/5248',
  '20:15',
  'Hyderabad',
  '01:30',
  '+ 1 day',
  'Mumbai',
  '5h 15m',
  '1 Stop',
  '9,622',
  'View Fares',
  'Flight Details',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,900 OFF. Use code: FLYNOW',
  'IndiGo',
  '6E-741/5248',
  '16:15',
  'Hyderabad',
  '01:30',
  '+ 1 day',
  'Mumbai',
  '9h 15m',
  '1 Stop',
  '9,622',
  'View Fares',
  'Flight Details',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,500 OFF. Use code: FLYNOW',
  'Go First',
  'G8-571/380',
  '20:20',
  'Hyderabad',
  '01:20',
  '+ 1 day',
  'Mumbai',
  '5h 00m',
  '1 Stop',
  '9,623',
  'View Fares',
  'Flight Details',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,500 OFF. Use code: FLYNOW',
  'Go First',
  'G8-571/381',
  '20:20',
  'Hyderabad',
  '08:00',
  '+ 1 day',
  'Mumbai',
  '11h 40m',
  '1 Stop',
  '9,623',
  'View Fares',
  'Flight Details',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,900 OFF. Use code: FLYNOW',
  'IndiGo',
  '6E-741/6386',
  '16:15',
  'Hyderabad',
  '19:45',
  'Mumbai',
  '3h 30m',
  '1 Stop',
  '1 left at9,832',
  'View Fares',
  'Flight Details',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,900 OFF. Use code: FLYNOW',
  'IndiGo',
  '6E-367/6386',
  '13:35',
  'Hyderabad',
  '19:45',
  'Mumbai',
  '6h 10m',
  '1 Stop',
  '1 left at9,832',
  'View Fares',
  'Flight Details',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,900 OFF. Use code: FLYNOW',
  'IndiGo',
  '6E-831/6386',
  '12:40',
  'Hyderabad',
  '19:45',
  'Mumbai',
  '7h 05m',
  '1 Stop',
  '1 left at9,832',
  'View Fares',
  'Flight Details',
  'eCash 250'],
 ['DEALBook this flight and get upto Rs. 1,500 OFF. Use code: FLYNOW',
  'SpiceJet',
  'SG-3736/487',
  '19:10',
  'Hyderabad',
  '18:50',
  '+ 1 day',
  'Mumbai',
  '23h 40m',
  '1 Stop',
  '9,885',
  'View Fares',
  'Flight Details',
  'eCash 250']]

In [38]:
df1_HYD_MUM_26apr=pd.DataFrame(HYD_MUM_26apr)
df1_HYD_MUM_26apr

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-878,12:55,Hyderabad,14:30,Mumbai,1h 35m,Non Stop,"1 left at5,528",Book Now,Flight Details,Free Meal,Emissions: 169 Kg CO2,eCash 250,None
1,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5316,21:45,Hyderabad,23:10,Mumbai,1h 25m,Non Stop,"4 left at6,105",View Fares,Flight Details,eCash 250,None,None,None
2,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-876,21:35,Hyderabad,23:00,Mumbai,1h 25m,Non Stop,"1 left at6,263",Book Now,Flight Details,Free Meal,Emissions: 169 Kg CO2,eCash 250,None
3,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6699,13:15,Hyderabad,14:45,Mumbai,1h 30m,Non Stop,"4 left at6,315",View Fares,Flight Details,eCash 250,None,None,None
4,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-972/472,16:35,Hyderabad,23:45,Mumbai,7h 10m,1 Stop,"6,655",View Fares,Flight Details,eCash 250,None,None,None
5,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/334,20:20,Hyderabad,00:20,+ 1 day,Mumbai,4h 00m,1 Stop,"7,522",View Fares,Flight Details,eCash 250,None,None
6,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/334,14:20,Hyderabad,00:20,+ 1 day,Mumbai,10h 00m,1 Stop,"7,522",View Fares,Flight Details,eCash 250,None,None
7,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5389,19:15,Hyderabad,20:35,Mumbai,1h 20m,Non Stop,"2 left at7,785",View Fares,Flight Details,eCash 250,None,None,None
8,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-840/887,20:40,Hyderabad,09:05,+ 1 day,Mumbai,12h 25m,1 Stop,"8,009",Book Now,Flight Details,Free Meal,eCash 250,None
9,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-840/665,20:40,Hyderabad,10:10,+ 1 day,Mumbai,13h 30m,1 Stop,"8,009",Book Now,Flight Details,Free Meal,Emissions: 652 Kg CO2,eCash 250
10,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-840/865,20:40,Hyderabad,12:35,+ 1 day,Mumbai,15h 55m,1 Stop,"8,009",Book Now,Flight Details,Free Meal,eCash 250,None
11,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-840/863,20:40,Hyderabad,16:15,+ 1 day,Mumbai,19h 35m,1 Stop,"8,009",Book Now,Flight Details,Free Meal,eCash 250,None
12,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-840/624,20:40,Hyderabad,21:15,+ 1 day,Mumbai,24h 35m,1 Stop,"8,009",Book Now,Flight Details,Free Meal,eCash 250,None
13,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-840/441,20:40,Hyderabad,21:35,+ 1 day,Mumbai,24h 55m,2 Stop(s),"8,009",Book Now,Flight Details,Free Meal,eCash 250,None
14,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-3736/454,19:10,Hyderabad,14:55,+ 1 day,Mumbai,19h 45m,1 Stop,"8,751",View Fares,Flight Details,eCash 250,None,None
15,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-840/636,20:40,Hyderabad,18:10,+ 1 day,Mumbai,21h 30m,2 Stop(s),"8,933",Book Now,Flight Details,Free Meal,eCash 250,None
16,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6433/5248,21:40,Hyderabad,01:30,+ 1 day,Mumbai,3h 50m,1 Stop,"9,622",View Fares,Flight Details,eCash 250,None,None
17,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-309/5248,20:15,Hyderabad,01:30,+ 1 day,Mumbai,5h 15m,1 Stop,"9,622",View Fares,Flight Details,eCash 250,None,None
18,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-741/5248,16:15,Hyderabad,01:30,+ 1 day,Mumbai,9h 15m,1 Stop,"9,622",View Fares,Flight Details,eCash 250,None,None
19,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-571/380,20:20,Hyderabad,01:20,+ 1 day,Mumbai,5h 00m,1 Stop,"9,623",View Fares,Flight Details,eCash 250,None,None
20,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-571/381,20:20,Hyderabad,08:00,+ 1 day,Mumbai,11h 40m,1 Stop,"9,623",View Fares,Flight Details,eCash 250,None,None
21,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-741/6386,16:15,Hyderabad,19:45,Mumbai,3h 30m,1 Stop,"1 left at9,832",View Fares,Flight Details,eCash 250,None,None,None
22,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-367/6386,13:35,Hyderabad,19:45,Mumbai,6h 10m,1 Stop,"1 left at9,832",View Fares,Flight Details,eCash 250,None,None,None
23,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-831/6386,12:40,Hyderabad,19:45,Mumbai,7h 05m,1 Stop,"1 left at9,832",View Fares,Flight Details,eCash 250,None,None,None
24,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-3736/487,19:10,Hyderabad,18:50,+ 1 day,Mumbai,23h 40m,1 Stop,"9,885",View Fares,Flight Details,eCash 250,None,None

In [42]:
writer=pd.ExcelWriter("df1_HYD_MUM_26apr.xlsx")
df1_HYD_MUM_26apr.to_excel(writer,"26apr", header=True, index= False)
writer.save()

## Manuall selected 10 days later flight(repeated till next 4 month' )
6 may
#16-may
#26 May
#6 June
16 June
26 june
6 Jul
16 july
26 July
6 aug
16 aug
26 aug
6 sep

In [48]:
HYD_MUM_6May = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     HYD_MUM_6May.append(i.text.split('\n'))
df2_HYD_MUM_6May=pd.DataFrame(HYD_MUM_6May)
df2_HYD_MUM_6May
writer=pd.ExcelWriter("df2_HYD_MUM_6May.xlsx")
df2_HYD_MUM_6May.to_excel(writer,"26apr", header=True, index= False)
writer.save()

In [49]:
HYD_MUM_16May = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     HYD_MUM_16May.append(i.text.split('\n'))
df_HYD_MUM_16May=pd.DataFrame(HYD_MUM_16May)

#writing in Excel
writer=pd.ExcelWriter("df_HYD_MUM_16May.xlsx")
df_HYD_MUM_16May.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_MUM_16May

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-509,08:35,Hyderabad,10:00,Mumbai,1h 25m,Non Stop,"4,476",View Fares,Flight Details,eCash 250,None,None
1,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5389,19:15,Hyderabad,20:35,Mumbai,1h 20m,Non Stop,"4,477",View Fares,Flight Details,eCash 250,None,None
2,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6106,04:15,Hyderabad,05:40,Mumbai,1h 25m,Non Stop,"4,477",View Fares,Flight Details,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5387,10:45,Hyderabad,12:10,Mumbai,1h 25m,Non Stop,"4,477",View Fares,Flight Details,eCash 250,None,None
4,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6268,17:50,Hyderabad,19:15,Mumbai,1h 25m,Non Stop,"4,477",View Fares,Flight Details,eCash 250,None,None
5,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5316,21:45,Hyderabad,23:10,Mumbai,1h 25m,Non Stop,"4,477",View Fares,Flight Details,eCash 250,None,None
6,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-199,06:45,Hyderabad,08:15,Mumbai,1h 30m,Non Stop,"4,477",View Fares,Flight Details,eCash 250,None,None
7,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6699,13:15,Hyderabad,14:45,Mumbai,1h 30m,Non Stop,"4,477",View Fares,Flight Details,eCash 250,None,None
8,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-163,08:10,Hyderabad,09:45,Mumbai,1h 35m,Non Stop,"4,477",View Fares,Flight Details,eCash 250,None,None
9,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-876,21:35,Hyderabad,23:00,Mumbai,1h 25m,Non Stop,"1 left at4,478",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
10,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-872,07:10,Hyderabad,08:40,Mumbai,1h 30m,Non Stop,"4,478",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
11,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-874,08:30,Hyderabad,10:00,Mumbai,1h 30m,Non Stop,"4,478",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
12,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-878,12:55,Hyderabad,14:30,Mumbai,1h 35m,Non Stop,"1 left at4,478",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
13,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-698,22:15,Hyderabad,23:50,Mumbai,1h 35m,Non Stop,"4,478",View Fares,Flight Details,Free Meal,Emissions: 169 Kg CO2,eCash 250
14,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/334,20:20,Hyderabad,00:20,+ 1 day,Mumbai,4h 00m,1 Stop,"6,655",View Fares,Flight Details,eCash 250,None
15,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/472,18:00,Hyderabad,23:45,Mumbai,5h 45m,1 Stop,"6,655",View Fares,Flight Details,eCash 250,None,None
16,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/612,14:20,Hyderabad,20:40,Mumbai,6h 20m,1 Stop,"6,655",View Fares,Flight Details,eCash 250,None,None
17,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/1782,14:20,Hyderabad,21:20,Mumbai,7h 00m,1 Stop,"6,655",View Fares,Flight Details,eCash 250,None,None
18,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-972/472,16:35,Hyderabad,23:45,Mumbai,7h 10m,1 Stop,"6,655",View Fares,Flight Details,eCash 250,None,None
19,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1518/941,21:55,Hyderabad,07:15,+ 1 day,Mumbai,9h 20m,1 Stop,"6,655",View Fares,Flight Details,eCash 250,None
20,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/334,14:20,Hyderabad,00:20,+ 1 day,Mumbai,10h 00m,1 Stop,"6,655",View Fares,Flight Details,eCash 250,None
21,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1231/941,21:10,Hyderabad,07:15,+ 1 day,Mumbai,10h 05m,1 Stop,"6,655",View Fares,Flight Details,eCash 250,None
22,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/941,20:20,Hyderabad,07:15,+ 1 day,Mumbai,10h 55m,1 Stop,"6,655",View Fares,Flight Details,eCash 250,None
23,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/335,18:00,Hyderabad,06:30,+ 1 day,Mumbai,12h 30m,1 Stop,"6,655",View Fares,Flight Details,eCash 250,None
24,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-3002,06:15,Hyderabad,10:35,Mumbai,4h 20m,1 Stop,"6,656",View Fares,Flight Details,eCash 250,None,None

In [53]:
HYD_MUM_26May = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     HYD_MUM_26May.append(i.text.split('\n'))
df_HYD_MUM_26May=pd.DataFrame(HYD_MUM_26May)

#writing in Excel
writer=pd.ExcelWriter("df_HYD_MUM_26May.xlsx")
df_HYD_MUM_26May.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_MUM_26May

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5389,19:15,Hyderabad,20:35,Mumbai,1h 20m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
1,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6106,04:15,Hyderabad,05:40,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
2,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-509,08:35,Hyderabad,10:00,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5387,10:45,Hyderabad,12:10,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
4,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6268,17:50,Hyderabad,19:15,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
5,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5316,21:45,Hyderabad,23:10,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
6,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-199,06:45,Hyderabad,08:15,Mumbai,1h 30m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
7,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6699,13:15,Hyderabad,14:45,Mumbai,1h 30m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
8,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-163,08:10,Hyderabad,09:45,Mumbai,1h 35m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
9,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-876,21:35,Hyderabad,23:00,Mumbai,1h 25m,Non Stop,"3,953",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
10,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-872,07:10,Hyderabad,08:40,Mumbai,1h 30m,Non Stop,"3,953",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
11,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-874,08:30,Hyderabad,10:00,Mumbai,1h 30m,Non Stop,"3,953",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
12,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-878,12:55,Hyderabad,14:30,Mumbai,1h 35m,Non Stop,"3,953",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
13,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-698,22:15,Hyderabad,23:50,Mumbai,1h 35m,Non Stop,"3,953",View Fares,Flight Details,Free Meal,Emissions: 169 Kg CO2,eCash 250
14,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/334,20:20,Hyderabad,00:20,+ 1 day,Mumbai,4h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
15,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/472,18:00,Hyderabad,23:45,Mumbai,5h 45m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
16,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/612,14:20,Hyderabad,20:40,Mumbai,6h 20m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
17,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/1782,14:20,Hyderabad,21:20,Mumbai,7h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
18,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-972/472,16:35,Hyderabad,23:45,Mumbai,7h 10m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
19,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1518/941,21:55,Hyderabad,07:15,+ 1 day,Mumbai,9h 20m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
20,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/334,14:20,Hyderabad,00:20,+ 1 day,Mumbai,10h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
21,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1231/941,21:10,Hyderabad,07:15,+ 1 day,Mumbai,10h 05m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
22,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/941,20:20,Hyderabad,07:15,+ 1 day,Mumbai,10h 55m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
23,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/335,18:00,Hyderabad,06:30,+ 1 day,Mumbai,12h 30m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
24,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-3002,06:15,Hyderabad,10:35,Mumbai,4h 20m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None,None

In [56]:
HYD_MUM_6June = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     HYD_MUM_6June.append(i.text.split('\n'))
df_HYD_MUM_6June=pd.DataFrame(HYD_MUM_6June)


#writing in Excel
writer=pd.ExcelWriter("df_HYD_MUM_6June.xlsx")
df_HYD_MUM_6June.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_MUM_6June

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5389,19:15,Hyderabad,20:35,Mumbai,1h 20m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
1,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6106,04:15,Hyderabad,05:40,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
2,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-509,08:35,Hyderabad,10:00,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5387,10:45,Hyderabad,12:10,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
4,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6268,17:50,Hyderabad,19:15,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
5,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5316,21:45,Hyderabad,23:10,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
6,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-199,06:45,Hyderabad,08:15,Mumbai,1h 30m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
7,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6699,13:15,Hyderabad,14:45,Mumbai,1h 30m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
8,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-163,08:10,Hyderabad,09:45,Mumbai,1h 35m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
9,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-876,21:35,Hyderabad,23:00,Mumbai,1h 25m,Non Stop,"3,953",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
10,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-872,07:10,Hyderabad,08:40,Mumbai,1h 30m,Non Stop,"3,953",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
11,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-874,08:30,Hyderabad,10:00,Mumbai,1h 30m,Non Stop,"3,953",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
12,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-878,12:55,Hyderabad,14:30,Mumbai,1h 35m,Non Stop,"3,953",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
13,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-698,22:15,Hyderabad,23:50,Mumbai,1h 35m,Non Stop,"4 left at3,953",View Fares,Flight Details,Free Meal,Emissions: 169 Kg CO2,eCash 250
14,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-7417/7291,09:40,Hyderabad,14:25,Mumbai,4h 45m,1 Stop,"1 left at4,573",View Fares,Flight Details,eCash 250,None,None
15,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/334,20:20,Hyderabad,00:20,+ 1 day,Mumbai,4h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
16,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/472,18:00,Hyderabad,23:45,Mumbai,5h 45m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
17,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/612,14:20,Hyderabad,20:40,Mumbai,6h 20m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
18,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/1782,14:20,Hyderabad,21:20,Mumbai,7h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
19,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-972/472,16:35,Hyderabad,23:45,Mumbai,7h 10m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
20,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1518/941,21:55,Hyderabad,07:15,+ 1 day,Mumbai,9h 20m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
21,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/334,14:20,Hyderabad,00:20,+ 1 day,Mumbai,10h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
22,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1231/941,21:10,Hyderabad,07:15,+ 1 day,Mumbai,10h 05m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
23,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/941,20:20,Hyderabad,07:15,+ 1 day,Mumbai,10h 55m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
24,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/335,18:00,Hyderabad,06:30,+ 1 day,Mumbai,12h 30m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None

In [57]:
HYD_MUM_16June = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     HYD_MUM_16June.append(i.text.split('\n'))
df_HYD_MUM_16June=pd.DataFrame(HYD_MUM_16June)


#writing in Excel
writer=pd.ExcelWriter("df_HYD_MUM_16June.xlsx")
df_HYD_MUM_16June.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_MUM_16June

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5389,19:15,Hyderabad,20:35,Mumbai,1h 20m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
1,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6106,04:15,Hyderabad,05:40,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
2,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-509,08:35,Hyderabad,10:00,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5387,10:45,Hyderabad,12:10,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
4,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6268,17:50,Hyderabad,19:15,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
5,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5316,21:45,Hyderabad,23:10,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
6,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-199,06:45,Hyderabad,08:15,Mumbai,1h 30m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
7,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6699,13:15,Hyderabad,14:45,Mumbai,1h 30m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
8,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-163,08:10,Hyderabad,09:45,Mumbai,1h 35m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
9,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-876,21:35,Hyderabad,23:00,Mumbai,1h 25m,Non Stop,"3,953",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
10,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-872,07:10,Hyderabad,08:40,Mumbai,1h 30m,Non Stop,"3,953",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
11,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-874,08:30,Hyderabad,10:00,Mumbai,1h 30m,Non Stop,"3,953",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
12,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-878,12:55,Hyderabad,14:30,Mumbai,1h 35m,Non Stop,"3,953",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
13,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-698,22:15,Hyderabad,23:50,Mumbai,1h 35m,Non Stop,"3,953",View Fares,Flight Details,Free Meal,Emissions: 169 Kg CO2,eCash 250
14,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-7417/7291,09:40,Hyderabad,14:25,Mumbai,4h 45m,1 Stop,"2 left at4,573",View Fares,Flight Details,eCash 250,None,None
15,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/334,20:20,Hyderabad,00:20,+ 1 day,Mumbai,4h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
16,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/472,18:00,Hyderabad,23:45,Mumbai,5h 45m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
17,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/612,14:20,Hyderabad,20:40,Mumbai,6h 20m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
18,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/1782,14:20,Hyderabad,21:20,Mumbai,7h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
19,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-972/472,16:35,Hyderabad,23:45,Mumbai,7h 10m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
20,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1518/941,21:55,Hyderabad,07:15,+ 1 day,Mumbai,9h 20m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
21,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/334,14:20,Hyderabad,00:20,+ 1 day,Mumbai,10h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
22,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1231/941,21:10,Hyderabad,07:15,+ 1 day,Mumbai,10h 05m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
23,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/941,20:20,Hyderabad,07:15,+ 1 day,Mumbai,10h 55m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
24,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/335,18:00,Hyderabad,06:30,+ 1 day,Mumbai,12h 30m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None

In [29]:
HYD_MUM_26June = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     HYD_MUM_26June.append(i.text.split('\n'))
df_HYD_MUM_26June=pd.DataFrame(HYD_MUM_26June)

#display the dataframe
df_HYD_MUM_26June

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-876,21:35,Hyderabad,23:00,Mumbai,1h 25m,Non Stop,"3,250",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
1,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-199,06:45,Hyderabad,08:15,Mumbai,1h 30m,Non Stop,"3,250",View Fares,Flight Details,eCash 250,None,None
2,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-872,07:10,Hyderabad,08:40,Mumbai,1h 30m,Non Stop,"3,250",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
3,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-874,08:30,Hyderabad,10:00,Mumbai,1h 30m,Non Stop,"3,250",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
4,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-163,08:10,Hyderabad,09:45,Mumbai,1h 35m,Non Stop,"3,250",View Fares,Flight Details,eCash 250,None,None
5,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-878,12:55,Hyderabad,14:30,Mumbai,1h 35m,Non Stop,"3,250",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
6,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5389,19:15,Hyderabad,20:35,Mumbai,1h 20m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
7,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6106,04:15,Hyderabad,05:40,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
8,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-509,08:35,Hyderabad,10:00,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
9,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5387,10:45,Hyderabad,12:10,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
10,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6268,17:50,Hyderabad,19:15,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
11,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5316,21:45,Hyderabad,23:10,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
12,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6699,13:15,Hyderabad,14:45,Mumbai,1h 30m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
13,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-698,22:15,Hyderabad,23:50,Mumbai,1h 35m,Non Stop,"3,953",View Fares,Flight Details,Free Meal,Emissions: 169 Kg CO2,eCash 250
14,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-7417/7291,09:40,Hyderabad,14:25,Mumbai,4h 45m,1 Stop,"4,258",View Fares,Flight Details,eCash 250,None,None
15,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/334,20:20,Hyderabad,00:20,+ 1 day,Mumbai,4h 00m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
16,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-3002,06:15,Hyderabad,10:35,Mumbai,4h 20m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None,None
17,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/472,18:00,Hyderabad,23:45,Mumbai,5h 45m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None,None
18,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/612,14:20,Hyderabad,20:40,Mumbai,6h 20m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None,None
19,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/1782,14:20,Hyderabad,21:20,Mumbai,7h 00m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None,None
20,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-972/472,16:35,Hyderabad,23:45,Mumbai,7h 10m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None,None
21,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1518/941,21:55,Hyderabad,07:15,+ 1 day,Mumbai,9h 20m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
22,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/334,14:20,Hyderabad,00:20,+ 1 day,Mumbai,10h 00m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
23,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1231/941,21:10,Hyderabad,07:15,+ 1 day,Mumbai,10h 05m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
24,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/941,20:20,Hyderabad,07:15,+ 1 day,Mumbai,10h 55m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None

In [58]:

#writing in Excel
writer=pd.ExcelWriter("df_HYD_MUM_26June.xlsx")
df_HYD_MUM_26June.to_excel(writer,"sheet", header=True, index= False)
writer.save()

In [30]:
HYD_MUM_6July = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     HYD_MUM_6July.append(i.text.split('\n'))
df_HYD_MUM_6July=pd.DataFrame(HYD_MUM_6July)

#display the dataframe
df_HYD_MUM_6July

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5387,10:45,Hyderabad,12:10,Mumbai,1h 25m,Non Stop,"1 left at3,250",View Fares,Flight Details,eCash 250,None,None
1,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-876,21:35,Hyderabad,23:00,Mumbai,1h 25m,Non Stop,"3,250",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
2,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-199,06:45,Hyderabad,08:15,Mumbai,1h 30m,Non Stop,"3,250",View Fares,Flight Details,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-872,07:10,Hyderabad,08:40,Mumbai,1h 30m,Non Stop,"3,250",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
4,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-874,08:30,Hyderabad,10:00,Mumbai,1h 30m,Non Stop,"3,250",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
5,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-163,08:10,Hyderabad,09:45,Mumbai,1h 35m,Non Stop,"1 left at3,250",View Fares,Flight Details,eCash 250,None,None
6,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-878,12:55,Hyderabad,14:30,Mumbai,1h 35m,Non Stop,"3,250",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
7,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5389,19:15,Hyderabad,20:35,Mumbai,1h 20m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
8,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6106,04:15,Hyderabad,05:40,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
9,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6268,17:50,Hyderabad,19:15,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
10,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5316,21:45,Hyderabad,23:10,Mumbai,1h 25m,Non Stop,"2 left at3,952",View Fares,Flight Details,eCash 250,None,None
11,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6699,13:15,Hyderabad,14:45,Mumbai,1h 30m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
12,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-741/6386,16:15,Hyderabad,19:45,Mumbai,3h 30m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
13,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6433/5248,21:40,Hyderabad,01:30,+ 1 day,Mumbai,3h 50m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None
14,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-7156/6569,14:35,Hyderabad,18:40,Mumbai,4h 05m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
15,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-7417/7291,09:40,Hyderabad,14:25,Mumbai,4h 45m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
16,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-309/5248,20:15,Hyderabad,01:30,+ 1 day,Mumbai,5h 15m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None
17,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-831/6386,12:40,Hyderabad,19:45,Mumbai,7h 05m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
18,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-743/6097,05:35,Hyderabad,14:30,Mumbai,8h 55m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
19,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-741/5248,16:15,Hyderabad,01:30,+ 1 day,Mumbai,9h 15m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None
20,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-698,22:15,Hyderabad,23:50,Mumbai,1h 35m,Non Stop,"3,953",View Fares,Flight Details,Free Meal,Emissions: 169 Kg CO2,eCash 250
21,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-831/714,12:40,Hyderabad,17:55,Mumbai,5h 15m,1 Stop,"3 left at4,792",View Fares,Flight Details,eCash 250,None,None
22,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/334,20:20,Hyderabad,00:20,+ 1 day,Mumbai,4h 00m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
23,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-3002,06:15,Hyderabad,10:35,Mumbai,4h 20m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None,None
24,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/472,18:00,Hyderabad,23:45,Mumbai,5h 45m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None,None

In [59]:
#writing in Excel
writer=pd.ExcelWriter("df_HYD_MUM_6July.xlsx")
df_HYD_MUM_6July.to_excel(writer,"sheet", header=True, index= False)
writer.save()

In [31]:
HYD_MUM_16July = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     HYD_MUM_16July.append(i.text.split('\n'))
df_HYD_MUM_16July=pd.DataFrame(HYD_MUM_16July)


#display the dataframe
df_HYD_MUM_16July

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-876,21:35,Hyderabad,23:00,Mumbai,1h 25m,Non Stop,"3,250",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
1,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5316,21:45,Hyderabad,23:10,Mumbai,1h 25m,Non Stop,"3,250",View Fares,Flight Details,eCash 250,None,None
2,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-199,06:45,Hyderabad,08:15,Mumbai,1h 30m,Non Stop,"3,250",View Fares,Flight Details,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-872,07:10,Hyderabad,08:40,Mumbai,1h 30m,Non Stop,"3,250",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
4,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-874,08:30,Hyderabad,10:00,Mumbai,1h 30m,Non Stop,"3,250",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
5,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-163,08:10,Hyderabad,09:45,Mumbai,1h 35m,Non Stop,"3,250",View Fares,Flight Details,eCash 250,None,None
6,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-878,12:55,Hyderabad,14:30,Mumbai,1h 35m,Non Stop,"3,250",View Fares,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
7,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6106,04:15,Hyderabad,05:40,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
8,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5387,10:45,Hyderabad,12:10,Mumbai,1h 25m,Non Stop,"3 left at3,952",View Fares,Flight Details,eCash 250,None,None
9,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6268,17:50,Hyderabad,19:15,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
10,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6699,13:15,Hyderabad,14:45,Mumbai,1h 30m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
11,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-741/6386,16:15,Hyderabad,19:45,Mumbai,3h 30m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
12,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6433/5248,21:40,Hyderabad,01:30,+ 1 day,Mumbai,3h 50m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None
13,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-7156/6569,14:35,Hyderabad,18:40,Mumbai,4h 05m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
14,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-7417/7291,09:40,Hyderabad,14:25,Mumbai,4h 45m,1 Stop,"1 left at3,952",View Fares,Flight Details,eCash 250,None,None
15,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-831/714,12:40,Hyderabad,17:55,Mumbai,5h 15m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
16,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-309/5248,20:15,Hyderabad,01:30,+ 1 day,Mumbai,5h 15m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None
17,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-7136/6292,10:55,Hyderabad,16:55,Mumbai,6h 00m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
18,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-831/6386,12:40,Hyderabad,19:45,Mumbai,7h 05m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
19,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-743/6097,05:35,Hyderabad,14:30,Mumbai,8h 55m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
20,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-741/5248,16:15,Hyderabad,01:30,+ 1 day,Mumbai,9h 15m,1 Stop,"3,952",View Fares,Flight Details,eCash 250,None
21,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-698,22:15,Hyderabad,23:50,Mumbai,1h 35m,Non Stop,"3,953",View Fares,Flight Details,Free Meal,Emissions: 169 Kg CO2,eCash 250
22,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5389,19:15,Hyderabad,20:35,Mumbai,1h 20m,Non Stop,"4,162",View Fares,Flight Details,eCash 250,None,None
23,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/334,20:20,Hyderabad,00:20,+ 1 day,Mumbai,4h 00m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
24,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-3002,06:15,Hyderabad,10:35,Mumbai,4h 20m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None,None

In [60]:

#writing in Excel
writer=pd.ExcelWriter("df_HYD_MUM_16July.xlsx")
df_HYD_MUM_16July.to_excel(writer,"sheet", header=True, index= False)
writer.save()

In [32]:
HYD_MUM_26July = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     HYD_MUM_26July.append(i.text.split('\n'))
df_HYD_MUM_26July=pd.DataFrame(HYD_MUM_26July)


#display the dataframe
df_HYD_MUM_26July

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5387,10:45,Hyderabad,12:10,Mumbai,1h 25m,Non Stop,"3,250",View Fares,Flight Details,eCash 250,None,None
1,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-876,21:35,Hyderabad,23:00,Mumbai,1h 25m,Non Stop,"3,250",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
2,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-199,06:45,Hyderabad,08:15,Mumbai,1h 30m,Non Stop,"3,250",View Fares,Flight Details,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-872,07:10,Hyderabad,08:40,Mumbai,1h 30m,Non Stop,"3,250",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
4,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-874,08:30,Hyderabad,10:00,Mumbai,1h 30m,Non Stop,"3,250",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
5,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6699,13:15,Hyderabad,14:45,Mumbai,1h 30m,Non Stop,"3,250",View Fares,Flight Details,eCash 250,None,None
6,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-878,12:55,Hyderabad,14:30,Mumbai,1h 35m,Non Stop,"3,250",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
7,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5389,19:15,Hyderabad,20:35,Mumbai,1h 20m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
8,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6106,04:15,Hyderabad,05:40,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
9,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6268,17:50,Hyderabad,19:15,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
10,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5316,21:45,Hyderabad,23:10,Mumbai,1h 25m,Non Stop,"3 left at3,952",View Fares,Flight Details,eCash 250,None,None
11,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-163,08:10,Hyderabad,09:45,Mumbai,1h 35m,Non Stop,"4,162",View Fares,Flight Details,eCash 250,None,None
12,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-7417/7291,09:40,Hyderabad,14:25,Mumbai,4h 45m,1 Stop,"4,258",View Fares,Flight Details,eCash 250,None,None
13,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-698,22:15,Hyderabad,23:50,Mumbai,1h 35m,Non Stop,"4,268",Book Now,Flight Details,Free Meal,Emissions: 169 Kg CO2,eCash 250
14,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/334,20:20,Hyderabad,00:20,+ 1 day,Mumbai,4h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
15,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/472,18:00,Hyderabad,23:45,Mumbai,5h 45m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
16,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/612,14:20,Hyderabad,20:40,Mumbai,6h 20m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
17,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/1782,14:20,Hyderabad,21:20,Mumbai,7h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
18,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-972/472,16:35,Hyderabad,23:45,Mumbai,7h 10m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
19,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1518/941,21:55,Hyderabad,07:15,+ 1 day,Mumbai,9h 20m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
20,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/334,14:20,Hyderabad,00:20,+ 1 day,Mumbai,10h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
21,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1231/941,21:10,Hyderabad,07:15,+ 1 day,Mumbai,10h 05m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
22,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/941,20:20,Hyderabad,07:15,+ 1 day,Mumbai,10h 55m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
23,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/335,18:00,Hyderabad,06:30,+ 1 day,Mumbai,12h 30m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
24,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-3002,06:15,Hyderabad,10:35,Mumbai,4h 20m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None,None

In [61]:

#writing in Excel
writer=pd.ExcelWriter("df_HYD_MUM_26July.xlsx")
df_HYD_MUM_26July.to_excel(writer,"sheet", header=True, index= False)
writer.save()

In [33]:
HYD_MUM_6Aug = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     HYD_MUM_6Aug.append(i.text.split('\n'))
df_HYD_MUM_6Aug=pd.DataFrame(HYD_MUM_6Aug)



#display the dataframe
df_HYD_MUM_6Aug

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-876,21:35,Hyderabad,23:00,Mumbai,1h 25m,Non Stop,"3,250",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
1,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-872,07:10,Hyderabad,08:40,Mumbai,1h 30m,Non Stop,"3,250",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
2,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-874,08:30,Hyderabad,10:00,Mumbai,1h 30m,Non Stop,"3,250",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
3,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6699,13:15,Hyderabad,14:45,Mumbai,1h 30m,Non Stop,"3 left at3,250",View Fares,Flight Details,eCash 250,None,None
4,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-878,12:55,Hyderabad,14:30,Mumbai,1h 35m,Non Stop,"3,250",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
5,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6106,04:15,Hyderabad,05:40,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
6,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5387,10:45,Hyderabad,12:10,Mumbai,1h 25m,Non Stop,"3 left at3,952",View Fares,Flight Details,eCash 250,None,None
7,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6268,17:50,Hyderabad,19:15,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
8,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5316,21:45,Hyderabad,23:10,Mumbai,1h 25m,Non Stop,"3 left at3,952",View Fares,Flight Details,eCash 250,None,None
9,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-199,06:45,Hyderabad,08:15,Mumbai,1h 30m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
10,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-698,22:15,Hyderabad,23:50,Mumbai,1h 35m,Non Stop,"3,953",Book Now,Flight Details,Free Meal,Emissions: 169 Kg CO2,eCash 250
11,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5389,19:15,Hyderabad,20:35,Mumbai,1h 20m,Non Stop,"4,162",View Fares,Flight Details,eCash 250,None,None
12,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-163,08:10,Hyderabad,09:45,Mumbai,1h 35m,Non Stop,"4,162",View Fares,Flight Details,eCash 250,None,None
13,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-7417/7291,09:40,Hyderabad,14:25,Mumbai,4h 45m,1 Stop,"3 left at4,258",View Fares,Flight Details,eCash 250,None,None
14,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/334,20:20,Hyderabad,00:20,+ 1 day,Mumbai,4h 00m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
15,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/472,18:00,Hyderabad,23:45,Mumbai,5h 45m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None,None
16,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1518/941,21:55,Hyderabad,07:15,+ 1 day,Mumbai,9h 20m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
17,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1231/941,21:10,Hyderabad,07:15,+ 1 day,Mumbai,10h 05m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
18,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/941,20:20,Hyderabad,07:15,+ 1 day,Mumbai,10h 55m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
19,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/335,18:00,Hyderabad,06:30,+ 1 day,Mumbai,12h 30m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
20,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-3002,06:15,Hyderabad,10:35,Mumbai,4h 20m,1 Stop,"5,868",View Fares,Flight Details,eCash 250,None,None
21,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-506/380,20:20,Hyderabad,01:10,+ 1 day,Mumbai,4h 50m,1 Stop,"6,102",View Fares,Flight Details,eCash 250,None
22,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-506/381,20:20,Hyderabad,08:00,+ 1 day,Mumbai,11h 40m,1 Stop,"6,102",View Fares,Flight Details,eCash 250,None
23,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-121/395,06:00,Hyderabad,10:05,Mumbai,4h 05m,1 Stop,"6,382",View Fares,Flight Details,eCash 250,None,None
24,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-121/320,06:00,Hyderabad,17:15,Mumbai,11h 15m,1 Stop,"6,382",View Fares,Flight Details,eCash 250,None,None

In [62]:
#writing in Excel
writer=pd.ExcelWriter("df_HYD_MUM_6Aug.xlsx")
df_HYD_MUM_6Aug.to_excel(writer,"sheet", header=True, index= False)
writer.save()

In [34]:
HYD_MUM_16Aug = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     HYD_MUM_16Aug.append(i.text.split('\n'))
df_HYD_MUM_16Aug=pd.DataFrame(HYD_MUM_16Aug)



#display the dataframe
df_HYD_MUM_16Aug

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-698,22:15,Hyderabad,23:50,Mumbai,1h 35m,Non Stop,"3 left at2,903",Book Now,Flight Details,Free Meal,Emissions: 169 Kg CO2,eCash 250
1,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5387,10:45,Hyderabad,12:10,Mumbai,1h 25m,Non Stop,"2 left at3,250",View Fares,Flight Details,eCash 250,None,None
2,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-199,06:45,Hyderabad,08:15,Mumbai,1h 30m,Non Stop,"2 left at3,250",View Fares,Flight Details,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6699,13:15,Hyderabad,14:45,Mumbai,1h 30m,Non Stop,"3 left at3,250",View Fares,Flight Details,eCash 250,None,None
4,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6106,04:15,Hyderabad,05:40,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
5,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6268,17:50,Hyderabad,19:15,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
6,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-876,21:35,Hyderabad,23:00,Mumbai,1h 25m,Non Stop,"3,953",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
7,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-872,07:10,Hyderabad,08:40,Mumbai,1h 30m,Non Stop,"3,953",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
8,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-874,08:30,Hyderabad,10:00,Mumbai,1h 30m,Non Stop,"3,953",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
9,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-878,12:55,Hyderabad,14:30,Mumbai,1h 35m,Non Stop,"3,953",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
10,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5389,19:15,Hyderabad,20:35,Mumbai,1h 20m,Non Stop,"4,162",View Fares,Flight Details,eCash 250,None,None
11,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-163,08:10,Hyderabad,09:45,Mumbai,1h 35m,Non Stop,"4,162",View Fares,Flight Details,eCash 250,None,None
12,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-7417/7291,09:40,Hyderabad,14:25,Mumbai,4h 45m,1 Stop,"4,258",View Fares,Flight Details,eCash 250,None,None
13,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5316,21:45,Hyderabad,23:10,Mumbai,1h 25m,Non Stop,"2 left at4,792",View Fares,Flight Details,eCash 250,None,None
14,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/334,20:20,Hyderabad,00:20,+ 1 day,Mumbai,4h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
15,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/472,18:00,Hyderabad,23:45,Mumbai,5h 45m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
16,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/612,14:20,Hyderabad,20:40,Mumbai,6h 20m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
17,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/1782,14:20,Hyderabad,21:20,Mumbai,7h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
18,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-972/472,16:35,Hyderabad,23:45,Mumbai,7h 10m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
19,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1518/941,21:55,Hyderabad,07:15,+ 1 day,Mumbai,9h 20m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
20,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/334,14:20,Hyderabad,00:20,+ 1 day,Mumbai,10h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
21,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1231/941,21:10,Hyderabad,07:15,+ 1 day,Mumbai,10h 05m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
22,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/941,20:20,Hyderabad,07:15,+ 1 day,Mumbai,10h 55m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
23,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/335,18:00,Hyderabad,06:30,+ 1 day,Mumbai,12h 30m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None
24,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-3002,06:15,Hyderabad,10:35,Mumbai,4h 20m,1 Stop,"5,868",View Fares,Flight Details,eCash 250,None,None

In [63]:

#writing in Excel
writer=pd.ExcelWriter("df_HYD_MUM_16Aug.xlsx")
df_HYD_MUM_16Aug.to_excel(writer,"sheet", header=True, index= False)
writer.save()

In [35]:
HYD_MUM_26Aug = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     HYD_MUM_26Aug.append(i.text.split('\n'))
df_HYD_MUM_26Aug=pd.DataFrame(HYD_MUM_26Aug)


#display the dataframe
df_HYD_MUM_26Aug

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-876,21:35,Hyderabad,23:00,Mumbai,1h 25m,Non Stop,"3,250",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250,None
1,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-872,07:10,Hyderabad,08:40,Mumbai,1h 30m,Non Stop,"3,250",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250,None
2,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-874,08:30,Hyderabad,10:00,Mumbai,1h 30m,Non Stop,"3,250",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250,None
3,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-878,12:55,Hyderabad,14:30,Mumbai,1h 35m,Non Stop,"3,250",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250,None
4,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-698,22:15,Hyderabad,23:50,Mumbai,1h 35m,Non Stop,"3,953",Book Now,Flight Details,Free Meal,Emissions: 169 Kg CO2,eCash 250,None
5,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/334,20:20,Hyderabad,00:20,+ 1 day,Mumbai,4h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
6,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/612,14:20,Hyderabad,20:40,Mumbai,6h 20m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None,None
7,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/1782,14:20,Hyderabad,21:20,Mumbai,7h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None,None
8,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1518/941,21:55,Hyderabad,07:15,+ 1 day,Mumbai,9h 20m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
9,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/334,14:20,Hyderabad,00:20,+ 1 day,Mumbai,10h 00m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
10,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1231/941,21:10,Hyderabad,07:15,+ 1 day,Mumbai,10h 05m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
11,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/941,20:20,Hyderabad,07:15,+ 1 day,Mumbai,10h 55m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
12,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/335,18:00,Hyderabad,06:30,+ 1 day,Mumbai,12h 30m,1 Stop,"4,792",View Fares,Flight Details,eCash 250,None,None
13,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-3002,06:15,Hyderabad,10:35,Mumbai,4h 20m,1 Stop,"5,868",View Fares,Flight Details,eCash 250,None,None,None
14,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-506/380,20:20,Hyderabad,01:10,+ 1 day,Mumbai,4h 50m,1 Stop,"6,102",View Fares,Flight Details,eCash 250,None,None
15,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-506/381,20:20,Hyderabad,08:00,+ 1 day,Mumbai,11h 40m,1 Stop,"6,102",View Fares,Flight Details,eCash 250,None,None
16,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-121/395,06:00,Hyderabad,10:05,Mumbai,4h 05m,1 Stop,"6,382",View Fares,Flight Details,eCash 250,None,None,None
17,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-121/320,06:00,Hyderabad,18:15,Mumbai,12h 15m,1 Stop,"6,382",View Fares,Flight Details,eCash 250,None,None,None
18,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-813/332,05:00,Hyderabad,14:40,Mumbai,9h 40m,1 Stop,"6,473",View Fares,Flight Details,eCash 250,None,None,None
19,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-898/852,07:30,Hyderabad,11:25,Mumbai,3h 55m,1 Stop,"6,486",Book Now,Flight Details,No Meal Fare,Emissions: 350 Kg CO2,eCash 250,None
20,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-894/866,18:25,Hyderabad,23:25,Mumbai,5h 00m,1 Stop,"6,486",Book Now,Flight Details,No Meal Fare,Emissions: 350 Kg CO2,eCash 250,None
21,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-898/854,07:30,Hyderabad,20:15,Mumbai,12h 45m,1 Stop,"6,486",Book Now,Flight Details,No Meal Fare,Emissions: 350 Kg CO2,eCash 250,None
22,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-898/864,07:30,Hyderabad,20:45,Mumbai,13h 15m,1 Stop,"6,486",Book Now,Flight Details,No Meal Fare,Emissions: 350 Kg CO2,eCash 250,None
23,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-894/858,18:25,Hyderabad,08:15,+ 1 day,Mumbai,13h 50m,1 Stop,"6,486",Book Now,Flight Details,No Meal Fare,Emissions: 350 Kg CO2,eCash 250
24,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-898/850,07:30,Hyderabad,21:50,Mumbai,14h 20m,1 Stop,"6,486",Book Now,Flight Details,No Meal Fare,Emissions: 350 Kg CO2,eCash 250,None

In [64]:
#writing in Excel
writer=pd.ExcelWriter("df_HYD_MUM_26Aug.xlsx")
df_HYD_MUM_26Aug.to_excel(writer,"sheet", header=True, index= False)
writer.save()

In [36]:
HYD_MUM_6sep = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     HYD_MUM_6sep.append(i.text.split('\n'))
df_HYD_MUM_6sep=pd.DataFrame(HYD_MUM_6sep)

#display the dataframe
df_HYD_MUM_6sep

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5387,10:45,Hyderabad,12:10,Mumbai,1h 25m,Non Stop,"3,250",View Fares,Flight Details,eCash 250,None,None
1,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-876,21:35,Hyderabad,23:00,Mumbai,1h 25m,Non Stop,"3,250",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
2,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-199,06:45,Hyderabad,08:15,Mumbai,1h 30m,Non Stop,"3,250",View Fares,Flight Details,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-872,07:10,Hyderabad,08:40,Mumbai,1h 30m,Non Stop,"3,250",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
4,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-874,08:30,Hyderabad,10:00,Mumbai,1h 30m,Non Stop,"3,250",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
5,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6699,13:15,Hyderabad,14:45,Mumbai,1h 30m,Non Stop,"3,250",View Fares,Flight Details,eCash 250,None,None
6,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-878,12:55,Hyderabad,14:30,Mumbai,1h 35m,Non Stop,"3,250",Book Now,Flight Details,No Meal Fare,Emissions: 169 Kg CO2,eCash 250
7,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6106,04:15,Hyderabad,05:40,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
8,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6268,17:50,Hyderabad,19:15,Mumbai,1h 25m,Non Stop,"3,952",View Fares,Flight Details,eCash 250,None,None
9,"DEALBook this flight and get upto Rs. 1,350 OF...",Air India,AI-698,22:15,Hyderabad,23:50,Mumbai,1h 35m,Non Stop,"1 left at3,953",Book Now,Flight Details,Free Meal,Emissions: 169 Kg CO2,eCash 250
10,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5389,19:15,Hyderabad,20:35,Mumbai,1h 20m,Non Stop,"4,162",View Fares,Flight Details,eCash 250,None,None
11,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5316,21:45,Hyderabad,23:10,Mumbai,1h 25m,Non Stop,"4,162",View Fares,Flight Details,eCash 250,None,None
12,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-163,08:10,Hyderabad,09:45,Mumbai,1h 35m,Non Stop,"4,162",View Fares,Flight Details,eCash 250,None,None
13,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-7417/7291,09:40,Hyderabad,14:25,Mumbai,4h 45m,1 Stop,"4,258",View Fares,Flight Details,eCash 250,None,None
14,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/334,20:20,Hyderabad,00:20,+ 1 day,Mumbai,4h 00m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
15,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/612,14:20,Hyderabad,20:40,Mumbai,6h 20m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None,None
16,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/1782,14:20,Hyderabad,21:20,Mumbai,7h 00m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None,None
17,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1518/941,21:55,Hyderabad,07:15,+ 1 day,Mumbai,9h 20m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
18,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1543/334,14:20,Hyderabad,00:20,+ 1 day,Mumbai,10h 00m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
19,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1231/941,21:10,Hyderabad,07:15,+ 1 day,Mumbai,10h 05m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
20,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-974/941,20:20,Hyderabad,07:15,+ 1 day,Mumbai,10h 55m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
21,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-1983/335,18:00,Hyderabad,06:30,+ 1 day,Mumbai,12h 30m,1 Stop,"5,134",View Fares,Flight Details,eCash 250,None
22,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-3002,06:15,Hyderabad,10:35,Mumbai,4h 20m,1 Stop,"5,868",View Fares,Flight Details,eCash 250,None,None
23,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-506/380,20:20,Hyderabad,01:10,+ 1 day,Mumbai,4h 50m,1 Stop,"6,102",View Fares,Flight Details,eCash 250,None
24,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-506/381,20:20,Hyderabad,08:00,+ 1 day,Mumbai,11h 40m,1 Stop,"6,102",View Fares,Flight Details,eCash 250,None

In [65]:
#writing in Excel
writer=pd.ExcelWriter("df_HYD_MUM_6sep.xlsx")
df_HYD_MUM_6sep.to_excel(writer,"sheet", header=True, index= False)
writer.save()

## trying to collect major trasport cities
## Delhi -Mumbai

In [87]:
driver=webdriver.Chrome(r'C:\Users\surendar.reddy\Documents\data Science projet_Data traine\chromedriver.exe')
time.sleep(3)

url = "https://flight.yatra.com/air-search-ui/dom2/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=BOM&destinationCountry=IN&flight_depart_date=26%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=fresco-flights&unqvaldesktop=1206718911299"
driver.get(url)

In [67]:
clear_ITEM1=driver.find_element_by_id("origin_0").clear()
time.sleep(2)
clear_ITEM2=driver.find_element_by_id("destination_0").clear()
time.sleep(2)

start_ITEM=driver.find_element_by_id("origin_0")
end_ITEM=driver.find_element_by_id("destination_0")
a=input(str("Enter ITEM start NAME: "))
b=input(str("Enter ITEM End NAME: "))
start_ITEM.send_keys(a)
time.sleep(10)
end_ITEM.send_keys(b)

time.sleep(5)
select_flight=driver.find_element_by_xpath('//button[@class="fs-14 btn-submit cursor-pointer bold"]').click()

Enter ITEM start NAME: Delhi
Enter ITEM End NAME: Mumbai

In [74]:
Del_MUM_26apr = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     Del_MUM_26apr.append(i.text.split('\n'))

#changing to dataframe
df_Del_MUM_26apr=pd.DataFrame(Del_MUM_26apr)

#writing in Excel
writer=pd.ExcelWriter("df_Del_MUM_26apr.xlsx")
df_Del_MUM_26apr.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_Del_MUM_26apr

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5318,17:00,New Delhi,19:05,Mumbai,2h 05m,Non Stop,"7,319",View Fares,Flight Details,eCash 250,None,None,None
1,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-2519,23:35,New Delhi,01:40,+ 1 day,Mumbai,2h 05m,Non Stop,"7,319",View Fares,Flight Details,eCash 250,None,None
2,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5306,15:25,New Delhi,17:35,Mumbai,2h 10m,Non Stop,"7,319",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-864,16:15,New Delhi,18:25,Mumbai,2h 10m,Non Stop,"7,319",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
4,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6261,19:45,New Delhi,21:55,Mumbai,2h 10m,Non Stop,"7,319",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-809/854,19:50,New Delhi,20:15,+ 1 day,Mumbai,24h 25m,1 Stop,"2 left at27,795",Book Now,Flight Details,Free Meal,Emissions: 517 Kg CO2,eCash 250
87,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-809/846,19:50,New Delhi,10:15,+ 1 day,Mumbai,14h 25m,1 Stop,"2 left at28,320",Book Now,Flight Details,Free Meal,Emissions: 517 Kg CO2,eCash 250
88,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-813/846,17:35,New Delhi,10:15,+ 1 day,Mumbai,16h 40m,1 Stop,"4 left at28,320",Book Now,Flight Details,Free Meal,Emissions: 517 Kg CO2,eCash 250
89,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-809/852,19:50,New Delhi,11:25,+ 1 day,Mumbai,15h 35m,1 Stop,"2 left at29,370",Book Now,Flight Details,Free Meal,Emissions: 517 Kg CO2,eCash 250
90,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-813/852,17:35,New Delhi,11:25,+ 1 day,Mumbai,17h 50m,1 Stop,"4 left at29,370",Book Now,Flight Details,Free Meal,Emissions: 517 Kg CO2,eCash 250

In [72]:

Del_MUM_6May = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     Del_MUM_6May.append(i.text.split('\n'))

#changing to dataframe
df_Del_MUM_6May=pd.DataFrame(Del_MUM_6May)

#writing in Excel
writer=pd.ExcelWriter("df_Del_MUM_6MAy.xlsx")
df_Del_MUM_6May.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_Del_MUM_6May

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-753,13:00,New Delhi,14:50,Mumbai,1h 50m,Non Stop,"7,319",View Fares,Flight Details,Emissions: 140 Kg CO2,eCash 250,None,None
1,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-2138,11:55,New Delhi,13:55,Mumbai,2h 00m,Non Stop,"7,319",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
2,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6814,07:20,New Delhi,09:25,Mumbai,2h 05m,Non Stop,"7,319",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5342,10:45,New Delhi,12:50,Mumbai,2h 05m,Non Stop,"7,319",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
4,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5318,17:00,New Delhi,19:05,Mumbai,2h 05m,Non Stop,"7,319",View Fares,Flight Details,eCash 250,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-819/866,14:15,New Delhi,23:25,Mumbai,9h 10m,1 Stop,"15,405",View Fares,Flight Details,Free Meal,Emissions: 517 Kg CO2,eCash 250,None
173,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8373/945,09:50,New Delhi,16:10,Mumbai,6h 20m,1 Stop,"15,914",View Fares,Flight Details,eCash 250,None,None,None
174,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8903/398,06:30,New Delhi,14:30,Mumbai,8h 00m,1 Stop,"17,819",View Fares,Flight Details,eCash 250,None,None,None
175,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8187/168,13:05,New Delhi,19:25,Mumbai,6h 20m,1 Stop,"19,919",View Fares,Flight Details,eCash 250,None,None,None
176,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8903/168,06:30,New Delhi,19:25,Mumbai,12h 55m,1 Stop,"19,919",View Fares,Flight Details,eCash 250,None,None,None

In [75]:
Del_MUM_16May = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     Del_MUM_16May.append(i.text.split('\n'))

#changing to dataframe
df_Del_MUM_16May=pd.DataFrame(Del_MUM_16May)

#writing in Excel
writer=pd.ExcelWriter("df_Del_MUM_16MAy.xlsx")
df_Del_MUM_16May.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_Del_MUM_16May

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-753,13:00,New Delhi,14:50,Mumbai,1h 50m,Non Stop,"5,849",View Fares,Flight Details,Emissions: 140 Kg CO2,eCash 250,None,None
1,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-2138,11:55,New Delhi,13:55,Mumbai,2h 00m,Non Stop,"5,849",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
2,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5023,06:30,New Delhi,08:35,Mumbai,2h 05m,Non Stop,"5,849",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6814,07:20,New Delhi,09:25,Mumbai,2h 05m,Non Stop,"5,849",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
4,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5342,10:45,New Delhi,12:50,Mumbai,2h 05m,Non Stop,"5,849",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-473/945,06:25,New Delhi,16:10,Mumbai,9h 45m,1 Stop,"22,108",View Fares,Flight Details,eCash 250,None,None,None
168,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-643/648,14:10,New Delhi,19:00,Mumbai,4h 50m,1 Stop,"23,753",View Fares,Flight Details,Free Meal,Emissions: 457 Kg CO2,eCash 250,None
169,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8903/168,06:30,New Delhi,19:25,Mumbai,12h 55m,1 Stop,"24,171",View Fares,Flight Details,eCash 250,None,None,None
170,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-611/648,10:30,New Delhi,19:00,Mumbai,8h 30m,1 Stop,"1 left at24,278",View Fares,Flight Details,Free Meal,Emissions: 457 Kg CO2,eCash 250,None
171,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8187/168,13:05,New Delhi,19:25,Mumbai,6h 20m,1 Stop,"24,853",View Fares,Flight Details,eCash 250,None,None,None

In [77]:
for _ in range(10000):
    driver.execute_script("window.scrollBy(0,10000)")
time.sleep(2)

Del_MUM_26May = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     Del_MUM_26May.append(i.text.split('\n'))

#changing to dataframe
df_Del_MUM_26May=pd.DataFrame(Del_MUM_26May)

#writing in Excel
writer=pd.ExcelWriter("df_Del_MUM_26MAy.xlsx")
df_Del_MUM_26May.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_Del_MUM_26May

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-2138,11:55,New Delhi,13:55,Mumbai,2h 00m,Non Stop,"4,799",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
1,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5023,06:30,New Delhi,08:35,Mumbai,2h 05m,Non Stop,"4,799",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
2,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6814,07:20,New Delhi,09:25,Mumbai,2h 05m,Non Stop,"4,799",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5342,10:45,New Delhi,12:50,Mumbai,2h 05m,Non Stop,"4,799",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
4,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-2009,02:00,New Delhi,04:10,Mumbai,2h 10m,Non Stop,"4,799",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8187/168,13:05,New Delhi,19:25,Mumbai,6h 20m,1 Stop,"22,543",View Fares,Flight Details,eCash 250,None,None,None
166,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-473/945,06:25,New Delhi,16:10,Mumbai,9h 45m,1 Stop,"23,474",View Fares,Flight Details,eCash 250,None,None,None
167,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-1010/287,12:10,New Delhi,18:25,Mumbai,6h 15m,1 Stop,"2 left at23,612",View Fares,Flight Details,eCash 250,None,None,None
168,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-213/287,11:50,New Delhi,18:25,Mumbai,6h 35m,1 Stop,"2 left at23,612",View Fares,Flight Details,eCash 250,None,None,None
169,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-191/287,09:25,New Delhi,18:25,Mumbai,9h 00m,1 Stop,"2 left at23,612",View Fares,Flight Details,eCash 250,None,None,None

In [79]:
for _ in range(10000):
    driver.execute_script("window.scrollBy(0,10000)")
time.sleep(2)

Del_MUM_6June = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     Del_MUM_6June.append(i.text.split('\n'))

#changing to dataframe
df_Del_MUM_6June=pd.DataFrame(Del_MUM_6June)

#writing in Excel
writer=pd.ExcelWriter("df_Del_MUM_6June.xlsx")
df_Del_MUM_6June.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_Del_MUM_6June

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-753,13:00,New Delhi,14:50,Mumbai,1h 50m,Non Stop,"4,799",View Fares,Flight Details,Emissions: 140 Kg CO2,eCash 250,None,None
1,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-2138,11:55,New Delhi,13:55,Mumbai,2h 00m,Non Stop,"4,799",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
2,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5023,06:30,New Delhi,08:35,Mumbai,2h 05m,Non Stop,"4,799",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6814,07:20,New Delhi,09:25,Mumbai,2h 05m,Non Stop,"4,799",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
4,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5342,10:45,New Delhi,12:50,Mumbai,2h 05m,Non Stop,"4,799",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8373/945,09:50,New Delhi,16:10,Mumbai,6h 20m,1 Stop,"17,594",View Fares,Flight Details,eCash 250,None,None,None
163,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8963/945,09:25,New Delhi,16:10,Mumbai,6h 45m,1 Stop,"17,594",View Fares,Flight Details,eCash 250,None,None,None
164,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-473/951,06:25,New Delhi,13:35,Mumbai,7h 10m,1 Stop,"19,798",View Fares,Flight Details,eCash 250,None,None,None
165,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-473/945,06:25,New Delhi,16:10,Mumbai,9h 45m,1 Stop,"20,744",View Fares,Flight Details,eCash 250,None,None,None
166,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8187/168,13:05,New Delhi,19:25,Mumbai,6h 20m,1 Stop,"22,123",View Fares,Flight Details,eCash 250,None,None,None

In [81]:
#for _ in range(100000):
#    driver.execute_script("window.scrollBy(0,100000)")
#time.sleep(2)

Del_MUM_16June = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     Del_MUM_16June.append(i.text.split('\n'))

#changing to dataframe
df_Del_MUM_16June=pd.DataFrame(Del_MUM_16June)

#writing in Excel
writer=pd.ExcelWriter("df_Del_MUM_16June.xlsx")
df_Del_MUM_16June.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_Del_MUM_16June

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,"DEALBook this flight and get upto Rs. 1,800 OF...",Air Asia,I5-753,13:00,New Delhi,14:50,Mumbai,1h 50m,Non Stop,"4,799",View Fares,Flight Details,Emissions: 140 Kg CO2,eCash 250,None,None
1,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-2138,11:55,New Delhi,13:55,Mumbai,2h 00m,Non Stop,"4,799",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
2,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5023,06:30,New Delhi,08:35,Mumbai,2h 05m,Non Stop,"4,799",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6814,07:20,New Delhi,09:25,Mumbai,2h 05m,Non Stop,"4,799",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
4,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5342,10:45,New Delhi,12:50,Mumbai,2h 05m,Non Stop,"4,799",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-190/386,05:20,New Delhi,11:30,Mumbai,6h 10m,1 Stop,"1 left at13,708",View Fares,Flight Details,eCash 250,None,None,None
158,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-191/3185,09:25,New Delhi,17:15,Mumbai,7h 50m,1 Stop,"2 left at14,128",View Fares,Flight Details,eCash 250,None,None,None
159,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8903/168,06:30,New Delhi,19:25,Mumbai,12h 55m,1 Stop,"15,193",View Fares,Flight Details,eCash 250,None,None,None
160,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-191/287,09:25,New Delhi,18:25,Mumbai,9h 00m,1 Stop,"2 left at15,284",View Fares,Flight Details,eCash 250,None,None,None
161,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8187/168,13:05,New Delhi,19:25,Mumbai,6h 20m,1 Stop,"18,239",View Fares,Flight Details,eCash 250,None,None,None

In [82]:
Del_MUM_26June = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     Del_MUM_26June.append(i.text.split('\n'))

#changing to dataframe
df_Del_MUM_26June=pd.DataFrame(Del_MUM_26June)

#writing in Excel
writer=pd.ExcelWriter("df_Del_MUM_26June.xlsx")
df_Del_MUM_26June.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_Del_MUM_26June

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-981,21:55,New Delhi,23:55,Mumbai,2h 00m,Non Stop,"4,373",View Fares,Flight Details,No Meal Fare,Emissions: 309 Kg CO2,eCash 250,None
1,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5023,06:30,New Delhi,08:35,Mumbai,2h 05m,Non Stop,"4,373",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
2,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6814,07:20,New Delhi,09:25,Mumbai,2h 05m,Non Stop,"4,373",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-2009,02:00,New Delhi,04:10,Mumbai,2h 10m,Non Stop,"4,373",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
4,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-2112,05:30,New Delhi,07:40,Mumbai,2h 10m,Non Stop,"4,373",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-829/876,07:05,New Delhi,23:00,Mumbai,15h 55m,1 Stop,"12,045",View Fares,Flight Details,No Meal Fare,Emissions: 512 Kg CO2,eCash 250,None
165,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8187/168,13:05,New Delhi,19:25,Mumbai,6h 20m,1 Stop,"12,989",View Fares,Flight Details,eCash 250,None,None,None
166,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8963/945,09:25,New Delhi,16:10,Mumbai,6h 45m,1 Stop,"13,288",View Fares,Flight Details,eCash 250,None,None,None
167,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-473/951,06:25,New Delhi,13:35,Mumbai,7h 10m,1 Stop,"14,234",View Fares,Flight Details,eCash 250,None,None,None
168,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-473/945,06:25,New Delhi,16:10,Mumbai,9h 45m,1 Stop,"15,914",View Fares,Flight Details,eCash 250,None,None,None

In [83]:
Del_MUM_6July = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     Del_MUM_6July.append(i.text.split('\n'))

#changing to dataframe
df_Del_MUM_6July=pd.DataFrame(Del_MUM_6July)

#writing in Excel
writer=pd.ExcelWriter("df_Del_MUM_6July.xlsx")
df_Del_MUM_6July.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_Del_MUM_6July

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-975,06:00,New Delhi,08:00,Mumbai,2h 00m,Non Stop,"4,373",View Fares,Flight Details,No Meal Fare,Emissions: 309 Kg CO2,eCash 250,None
1,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-981,21:55,New Delhi,23:55,Mumbai,2h 00m,Non Stop,"4,373",View Fares,Flight Details,No Meal Fare,Emissions: 309 Kg CO2,eCash 250,None
2,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5023,06:30,New Delhi,08:35,Mumbai,2h 05m,Non Stop,"4,373",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6814,07:20,New Delhi,09:25,Mumbai,2h 05m,Non Stop,"4,373",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
4,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-2009,02:00,New Delhi,04:10,Mumbai,2h 10m,Non Stop,"4,373",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8903/398,06:30,New Delhi,14:30,Mumbai,8h 00m,1 Stop,"9,778",View Fares,Flight Details,eCash 250,None,None,None
171,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8903/168,06:30,New Delhi,19:25,Mumbai,12h 55m,1 Stop,"9,778",View Fares,Flight Details,eCash 250,None,None,None
172,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-473/951,06:25,New Delhi,13:35,Mumbai,7h 10m,1 Stop,"11,961",View Fares,Flight Details,eCash 250,None,None,None
173,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-473/945,06:25,New Delhi,16:10,Mumbai,9h 45m,1 Stop,"12,351",View Fares,Flight Details,eCash 250,None,None,None
174,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-751/114,11:30,New Delhi,18:10,Mumbai,6h 40m,1 Stop,"14,590",View Fares,Flight Details,eCash 250,None,None,None

In [84]:
Del_MUM_16July = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     Del_MUM_16July.append(i.text.split('\n'))

#changing to dataframe
df_Del_MUM_16July=pd.DataFrame(Del_MUM_16July)

#writing in Excel
writer=pd.ExcelWriter("df_Del_MUM_16July.xlsx")
df_Del_MUM_16July.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_Del_MUM_16July

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-975,06:00,New Delhi,08:00,Mumbai,2h 00m,Non Stop,"4,373",View Fares,Flight Details,No Meal Fare,Emissions: 309 Kg CO2,eCash 250,None
1,"DEALBook this flight and get upto Rs. 1,500 OF...",Vistara,UK-981,21:55,New Delhi,23:55,Mumbai,2h 00m,Non Stop,"4,373",View Fares,Flight Details,No Meal Fare,Emissions: 309 Kg CO2,eCash 250,None
2,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-5023,06:30,New Delhi,08:35,Mumbai,2h 05m,Non Stop,"4,373",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
3,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-6814,07:20,New Delhi,09:25,Mumbai,2h 05m,Non Stop,"4,373",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
4,"DEALBook this flight and get upto Rs. 1,900 OF...",IndiGo,6E-2009,02:00,New Delhi,04:10,Mumbai,2h 10m,Non Stop,"4,373",View Fares,Flight Details,Emissions: 142 Kg CO2,eCash 250,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-8903/168,06:30,New Delhi,19:25,Mumbai,12h 55m,1 Stop,"9,778",View Fares,Flight Details,eCash 250,None,None,None
174,"DEALBook this flight and get upto Rs. 1,500 OF...",Go First,G8-191/287,09:25,New Delhi,18:25,Mumbai,9h 00m,1 Stop,"11,071",View Fares,Flight Details,eCash 250,None,None,None
175,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-473/951,06:25,New Delhi,13:35,Mumbai,7h 10m,1 Stop,"11,931",View Fares,Flight Details,eCash 250,None,None,None
176,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-473/945,06:25,New Delhi,16:10,Mumbai,9h 45m,1 Stop,"12,507",View Fares,Flight Details,eCash 250,None,None,None
177,"DEALBook this flight and get upto Rs. 1,500 OF...",SpiceJet,SG-751/114,11:30,New Delhi,18:10,Mumbai,6h 40m,1 Stop,"14,590",View Fares,Flight Details,eCash 250,None,None,None

In [88]:
Del_MUM_26July = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     Del_MUM_26July.append(i.text.split('\n'))

#changing to dataframe
df_Del_MUM_26July=pd.DataFrame(Del_MUM_26July)

#writing in Excel
writer=pd.ExcelWriter("df_Del_MUM_26July.xlsx")
df_Del_MUM_26July.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_Del_MUM_26July

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Vistara,UK-975,06:00,New Delhi,08:00,Mumbai,2h 00m,Non Stop,"4,373",Book Now,Flight Details,No Meal Fare,Emissions: 309 Kg CO,eCash 250,None
1,Vistara,UK-981,21:55,New Delhi,23:55,Mumbai,2h 00m,Non Stop,"4,373",Book Now,Flight Details,No Meal Fare,Emissions: 309 Kg CO,eCash 250,None
2,IndiGo,6E-5023,06:30,New Delhi,08:35,Mumbai,2h 05m,Non Stop,"4,373",View Fares,Flight Details,Emissions: 142 Kg CO,eCash 250,None,None
3,IndiGo,6E-6814,07:20,New Delhi,09:25,Mumbai,2h 05m,Non Stop,"4,373",View Fares,Flight Details,Emissions: 142 Kg CO,eCash 250,None,None
4,IndiGo,6E-5318,17:00,New Delhi,19:05,Mumbai,2h 05m,Non Stop,"4,373",View Fares,Flight Details,eCash 250,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,Air India,AI-407/732,13:45,New Delhi,12:05,+ 1 day,Mumbai,22h 20m,1 Stop,"9,976",Book Now,Flight Details,Free Meal,Emissions: 625 Kg CO,eCash 250
173,Vistara,UK-643/648,14:10,New Delhi,19:00,Mumbai,4h 50m,1 Stop,"10,145",Book Now,Flight Details,No Meal Fare,Emissions: 457 Kg CO,eCash 250,None
174,SpiceJet,SG-473/951,06:25,New Delhi,13:35,Mumbai,7h 10m,1 Stop,"11,961",View Fares,Flight Details,eCash 250,None,None,None
175,SpiceJet,SG-473/945,06:25,New Delhi,16:10,Mumbai,9h 45m,1 Stop,"12,351",View Fares,Flight Details,eCash 250,None,None,None
176,SpiceJet,SG-751/114,11:30,New Delhi,18:10,Mumbai,6h 40m,1 Stop,"14,590",View Fares,Flight Details,eCash 250,None,None,None

In [90]:
Del_MUM_6Aug = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     Del_MUM_6Aug.append(i.text.split('\n'))

#changing to dataframe
df_Del_MUM_6Aug=pd.DataFrame(Del_MUM_6Aug)

#writing in Excel
writer=pd.ExcelWriter("df_Del_MUM_6Aug.xlsx")
df_Del_MUM_6Aug.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_Del_MUM_6Aug

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,IndiGo,6E-5023,06:30,New Delhi,08:35,Mumbai,2h 05m,Non Stop,"2 left at4,373",View Fares,Flight Details,Emissions: 142 Kg CO,eCash 250,None,None
1,IndiGo,6E-6814,07:20,New Delhi,09:25,Mumbai,2h 05m,Non Stop,"2 left at4,373",View Fares,Flight Details,Emissions: 142 Kg CO,eCash 250,None,None
2,IndiGo,6E-5318,17:00,New Delhi,19:05,Mumbai,2h 05m,Non Stop,"2 left at4,373",View Fares,Flight Details,eCash 250,None,None,None
3,IndiGo,6E-2112,05:30,New Delhi,07:40,Mumbai,2h 10m,Non Stop,"1 left at4,373",View Fares,Flight Details,Emissions: 142 Kg CO,eCash 250,None,None
4,Go First,G8-530,06:50,New Delhi,08:55,Mumbai,2h 05m,Non Stop,"4,374",View Fares,Flight Details,eCash 250,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,SpiceJet,SG-8903/398,06:30,New Delhi,14:30,Mumbai,8h 00m,1 Stop,"10,556",View Fares,Flight Details,eCash 250,None,None,None
174,SpiceJet,SG-8903/168,06:30,New Delhi,19:25,Mumbai,12h 55m,1 Stop,"10,556",View Fares,Flight Details,eCash 250,None,None,None
175,SpiceJet,SG-473/945,06:25,New Delhi,16:10,Mumbai,9h 45m,1 Stop,"11,931",View Fares,Flight Details,eCash 250,None,None,None
176,SpiceJet,SG-473/951,06:25,New Delhi,13:35,Mumbai,7h 10m,1 Stop,"12,507",View Fares,Flight Details,eCash 250,None,None,None
177,SpiceJet,SG-751/114,11:30,New Delhi,18:10,Mumbai,6h 40m,1 Stop,"14,590",View Fares,Flight Details,eCash 250,None,None,None

In [91]:
Del_MUM_16Aug = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     Del_MUM_16Aug.append(i.text.split('\n'))

#changing to dataframe
df_Del_MUM_16Aug=pd.DataFrame(Del_MUM_16Aug)

#writing in Excel
writer=pd.ExcelWriter("df_Del_MUM_16Aug.xlsx")
df_Del_MUM_16Aug.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_Del_MUM_16Aug

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,IndiGo,6E-5023,06:30,New Delhi,08:35,Mumbai,2h 05m,Non Stop,"1 left at4,373",View Fares,Flight Details,Emissions: 142 Kg CO,eCash 250,None,None
1,IndiGo,6E-5318,17:00,New Delhi,19:05,Mumbai,2h 05m,Non Stop,"2 left at4,373",View Fares,Flight Details,eCash 250,None,None,None
2,IndiGo,6E-2112,05:30,New Delhi,07:40,Mumbai,2h 10m,Non Stop,"3 left at4,373",View Fares,Flight Details,Emissions: 142 Kg CO,eCash 250,None,None
3,Vistara,UK-953,20:40,New Delhi,22:50,Mumbai,2h 10m,Non Stop,"4,373",Book Now,Flight Details,No Meal Fare,Emissions: 309 Kg CO,eCash 250,None
4,Air Asia,I5-753,13:00,New Delhi,14:50,Mumbai,1h 50m,Non Stop,"4,374",Book Now,Flight Details,Emissions: 140 Kg CO,eCash 250,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,SpiceJet,SG-473/951,06:25,New Delhi,13:35,Mumbai,7h 10m,1 Stop,"11,511",View Fares,Flight Details,eCash 250,None,None,None
173,SpiceJet,SG-473/945,06:25,New Delhi,16:10,Mumbai,9h 45m,1 Stop,"11,511",View Fares,Flight Details,eCash 250,None,None,None
174,Vistara,UK-817/850,16:05,New Delhi,21:50,Mumbai,5h 45m,1 Stop,"11,730",Book Now,Flight Details,No Meal Fare,Emissions: 517 Kg CO,eCash 250,None
175,Vistara,UK-819/854,14:15,New Delhi,20:15,Mumbai,6h 00m,1 Stop,"11,730",Book Now,Flight Details,No Meal Fare,Emissions: 517 Kg CO,eCash 250,None
176,SpiceJet,SG-751/114,11:30,New Delhi,18:10,Mumbai,6h 40m,1 Stop,"14,590",View Fares,Flight Details,eCash 250,None,None,None

In [92]:
Del_MUM_26Aug = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     Del_MUM_26Aug.append(i.text.split('\n'))

#changing to dataframe
df_Del_MUM_26Aug=pd.DataFrame(Del_MUM_26Aug)

#writing in Excel
writer=pd.ExcelWriter("df_Del_MUM_26Aug.xlsx")
df_Del_MUM_26Aug.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_Del_MUM_26Aug

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,IndiGo,6E-5023,06:30,New Delhi,08:35,Mumbai,2h 05m,Non Stop,"3 left at4,373",View Fares,Flight Details,Emissions: 142 Kg CO,eCash 250,None,None
1,IndiGo,6E-6814,07:20,New Delhi,09:25,Mumbai,2h 05m,Non Stop,"3 left at4,373",View Fares,Flight Details,Emissions: 142 Kg CO,eCash 250,None,None
2,IndiGo,6E-5318,17:00,New Delhi,19:05,Mumbai,2h 05m,Non Stop,"2 left at4,373",View Fares,Flight Details,eCash 250,None,None,None
3,IndiGo,6E-2112,05:30,New Delhi,07:40,Mumbai,2h 10m,Non Stop,"4 left at4,373",View Fares,Flight Details,Emissions: 142 Kg CO,eCash 250,None,None
4,SpiceJet,SG-8701,07:20,New Delhi,09:35,Mumbai,2h 15m,Non Stop,"4,376",View Fares,Flight Details,eCash 250,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,SpiceJet,SG-8903/398,06:30,New Delhi,14:30,Mumbai,8h 00m,1 Stop,"10,556",View Fares,Flight Details,eCash 250,None,None,None
161,SpiceJet,SG-8903/168,06:30,New Delhi,19:25,Mumbai,12h 55m,1 Stop,"10,556",View Fares,Flight Details,eCash 250,None,None,None
162,SpiceJet,SG-473/951,06:25,New Delhi,13:35,Mumbai,7h 10m,1 Stop,"11,511",View Fares,Flight Details,eCash 250,None,None,None
163,SpiceJet,SG-473/945,06:25,New Delhi,16:10,Mumbai,9h 45m,1 Stop,"11,511",View Fares,Flight Details,eCash 250,None,None,None
164,SpiceJet,SG-751/114,11:30,New Delhi,18:10,Mumbai,6h 40m,1 Stop,"14,590",View Fares,Flight Details,eCash 250,None,None,None

In [93]:
Del_MUM_6Sep = []
for i in driver.find_elements_by_xpath('//div[@class="tuple"]'):
     Del_MUM_6Sep.append(i.text.split('\n'))

#changing to dataframe
df_Del_MUM_6Sep=pd.DataFrame(Del_MUM_6Sep)

#writing in Excel
writer=pd.ExcelWriter("df_Del_MUM_6Sep.xlsx")
df_Del_MUM_6Sep.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_Del_MUM_6Sep

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Vistara,UK-975,06:00,New Delhi,08:00,Mumbai,2h 00m,Non Stop,"4,373",Book Now,Flight Details,No Meal Fare,Emissions: 309 Kg CO,eCash 250,None
1,Vistara,UK-981,21:55,New Delhi,23:55,Mumbai,2h 00m,Non Stop,"4,373",Book Now,Flight Details,No Meal Fare,Emissions: 309 Kg CO,eCash 250,None
2,IndiGo,6E-5023,06:30,New Delhi,08:35,Mumbai,2h 05m,Non Stop,"4,373",View Fares,Flight Details,Emissions: 142 Kg CO,eCash 250,None,None
3,IndiGo,6E-6814,07:20,New Delhi,09:25,Mumbai,2h 05m,Non Stop,"4,373",View Fares,Flight Details,Emissions: 142 Kg CO,eCash 250,None,None
4,IndiGo,6E-5318,17:00,New Delhi,19:05,Mumbai,2h 05m,Non Stop,"4 left at4,373",View Fares,Flight Details,eCash 250,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,SpiceJet,SG-8903/398,06:30,New Delhi,14:30,Mumbai,8h 00m,1 Stop,"10,556",View Fares,Flight Details,eCash 250,None,None,None
173,SpiceJet,SG-8903/168,06:30,New Delhi,19:25,Mumbai,12h 55m,1 Stop,"10,556",View Fares,Flight Details,eCash 250,None,None,None
174,SpiceJet,SG-473/945,06:25,New Delhi,16:10,Mumbai,9h 45m,1 Stop,"11,121",View Fares,Flight Details,eCash 250,None,None,None
175,SpiceJet,SG-473/951,06:25,New Delhi,13:35,Mumbai,7h 10m,1 Stop,"11,511",View Fares,Flight Details,eCash 250,None,None,None
176,SpiceJet,SG-751/114,11:30,New Delhi,18:10,Mumbai,6h 40m,1 Stop,"14,590",View Fares,Flight Details,eCash 250,None,None,None

In [ ]:
### https://www.skyscanner.co.in

In [36]:
driver=webdriver.Chrome(r'C:\Users\surendar.reddy\Documents\data Science projet_Data traine\chromedriver.exe')
time.sleep(3)
url ="https://www.skyscanner.co.in/transport/flights/hyd/blr/220427/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&priceSourceId=&priceTrace=&qp_prevCurrency=INR&qp_prevPrice=OneWayNone&qp_prevProvider=ins_month&rtn=0"
driver.get(url)

In [35]:
HYD_BAN_27apr = []
HYD_BAN_27apr_AIRLINES = []
for i in driver.find_elements_by_xpath('//div[@class="FlightsTicket_container__NWJkY"]'):
     HYD_BAN_27apr.append(i.text.split('\n'))       
for i in driver.find_elements_by_xpath("//div[@class='BpkImage_bpk-image__NzYwO BpkImage_bpk-image--no-background__OTRiM']//img") :
     HYD_BAN_27apr_AIRLINES.append(i.get_attribute('alt'))

# slicing odd
HYD_BAN_27apr_AIRLINES  = HYD_BAN_27apr_AIRLINES[::2]

#changing to dataframe
df_HYD_BAN_27apr=pd.DataFrame(HYD_BAN_27apr)
df_HYD_BAN_27apr_AIRLINES=pd.DataFrame(HYD_BAN_27apr_AIRLINES)

#join the 2 data Frame
df_HYD_BAN_27apr = df_HYD_BAN_27apr.join(df_HYD_BAN_27apr_AIRLINES,how = 'right', lsuffix='_x')
#merged = df_train_csv.join(df_train_fly, how = 'right', lsuffix='_x')

#writing in Excel
writer=pd.ExcelWriter("df_HYD_BAN_27apr.xlsx")
df_HYD_BAN_27apr.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_BAN_27apr

,0_x,1,2,3,4,5,6,7,8,9,10,0
0,"Flight option 1: Total cost ₹ 5,050.",14:20,HYD,1h 10,Direct,15:30,BLR,13 deals from,"₹ 5,050",Select,None,AirAsia India
1,"Flight option 2: Total cost ₹ 4,673.",20:20,HYD,1h 20,Direct,21:40,BLR,17 deals from,"₹ 4,673",Select,None,AirAsia India
2,"Flight option 3: Total cost ₹ 5,788.",12:00,HYD,1h 10,Direct,13:10,BLR,11 deals from,"₹ 5,788",Select,None,IndiGo
3,"Flight option 5: Total cost ₹ 5,938.",18:25,HYD,1h 05,Direct,19:30,BLR,17 deals from,"₹ 5,938",Select,None,Vistara
4,"Flight option 6: Total cost ₹ 5,686.",20:30,HYD,1h 05,Direct,21:35,BLR,16 deals from,"₹ 5,686",Select,None,IndiGo
5,"Flight option 8: Total cost ₹ 5,998.",22:30,HYD,1h 10,Direct,23:40,BLR,17 deals from,"₹ 5,998",Select,None,IndiGo
6,"Flight option 9: Total cost ₹ 7,048.",18:10,HYD,1h 10,Direct,19:20,BLR,16 deals from,"₹ 7,048",Select,None,IndiGo
7,"Flight option 10: Total cost ₹ 7,258.",16:40,HYD,1h 15,Direct,17:55,BLR,16 deals from,"₹ 7,258",Select,None,IndiGo
8,"Flight option 11: Total cost ₹ 5,166.",13:30,HYD,4h 25,1 stop,BBI,17:55,BLR,12 deals from,"₹ 5,166",Select,Air India
9,"Flight option 13: Total cost ₹ 9,157.",13:35,HYD,3h 40,1 stop,MAA,17:15,BLR,12 deals from,"₹ 9,157",Select,IndiGo
10,"Flight option 14: Total cost ₹ 10,761.",16:20,HYD,3h 35,1 stop,MAA,19:55,BLR,16 deals from,"₹ 10,761",Select,IndiGo
11,"Flight option 15: Total cost ₹ 9,529.",12:55,HYD,4h 50,1 stop,BOM,17:45,BLR,12 deals from,"₹ 9,529",Select,Vistara
12,"Flight option 16: Total cost ₹ 12,771.",19:00,HYD,3h 20,1 stop,MAA,22:20,BLR,16 deals from,"₹ 12,771",Select,IndiGo
13,"Flight option 18: Total cost ₹ 12,094.",10:05,HYD,3h 55,1 stop,MAA,14:00,BLR,1 deal,"₹ 12,094",Select,IndiGo
14,"Flight option 19: Total cost ₹ 12,615.",17:55,HYD,4h 25,1 stop,MAA,22:20,BLR,2 deals from,"₹ 12,615",Select,IndiGo
15,"Flight option 20: Total cost ₹ 9,902.",16:20,HYD,6h,1 stop,MAA,22:20,BLR,15 deals from,"₹ 9,902",Select,IndiGo
16,"Flight option 21: Total cost ₹ 16,183.",12:50,HYD,4h 45,1 stop,TIR,17:35,BLR,2 deals from,"₹ 16,183",Select,IndiGo
17,"Flight option 23: Total cost ₹ 9,201.",23:15,HYD,9h 25,1 stop,MAA,08:40+1,BLR,8 deals from,"₹ 9,201",Select,IndiGo
18,"Flight option 24: Total cost ₹ 18,187.",18:05,HYD,5h,1 stop,VGA,23:05,BLR,13 deals from,"₹ 18,187",Select,IndiGo
19,"Flight option 25: Total cost ₹ 11,283.",21:35,HYD,10h 15,1 stop,BOM,07:50+1,BLR,9 deals from,"₹ 11,283",Select,Vistara
20,"Flight option 26: Total cost ₹ 10,841.",22:15,HYD,9h 35,1 stop,BOM,07:50+1,BLR,16 deals from,"₹ 10,841",Select,Air India
21,"Flight option 28: Total cost ₹ 18,204.",11:35,HYD,6h 40,1 stop,IXC,18:15,BLR,5 deals from,"₹ 18,204",Select,Vistara
22,"Flight option 29: Total cost ₹ 9,204.",12:55,HYD,18h 55,1 stop,BOM,07:50+1,BLR,5 deals from,"₹ 9,204",Select,Vistara
23,"Flight option 30: Total cost ₹ 23,638.",17:40,HYD,5h 40,1 stop,DEL,23:20,BLR,9 deals from,"₹ 23,638",Select,Vistara
24,"Flight option 31: Total cost ₹ 18,866.",10:55,HYD,7h 25,1 stop,VGA,18:20,BLR,1 deal,"₹ 18,866",Select,IndiGo
25,"Flight option 33: Total cost ₹ 14,900.",20:40,HYD,12h 15,1 stop,DEL,08:55+1,BLR,14 deals from,"₹ 14,900",Select,Air India
26,"Flight option 34: Total cost ₹ 12,588.",17:30,HYD,15h 05,1 stop,DEL,08:35+1,BLR,11 deals from,"₹ 12,588",Select,GoAir
27,"Flight option 35: Total cost ₹ 13,535.",17:40,HYD,15h 20,1 stop,DEL,09:00+1,BLR,9 deals from,"₹ 13,535",Select,Vistara
28,"Flight option 36: Total cost ₹ 16,918.",20:30,HYD,12h 30,1 stop,DEL,09:00+1,BLR,10 deals from,"₹ 16,918",Select,Vistara
29,"Flight option 38: Total cost ₹ 21,856.",13:25,HYD,9h 45,2 stops,"DEL, BOM",23:10,BLR,1 deal,"₹ 21,856",Select,Vistara
30,"Flight option 39: Total cost ₹ 27,190.",16:10,HYD,7h 55,1 stop,DEL,00:05+1,BLR,6 deals from,"₹ 27,190",Select,Air India
31,"Flight option 40: Total cost ₹ 13,049.",13:25,HYD,19h 35,1 stop,DEL,09:00+1,BLR,3 deals from,"₹ 13,049",Select,Vistara
32,"Flight option 41: Total cost ₹ 27,758.",13:25,HYD,9h 15,1 stop,DEL,22:40,BLR,3 deals from,"₹ 27,758",Select,Vistara
33,"Flight option 43: Total cost ₹ 24,293.",21:50,HYD,11h 05,1 stop,DXB,08:55+1,BLR,2 deals from,"₹ 24,293",Select,Emirates
34,"Flight option 44: Total cost ₹ 15,246.",22:15,HYD,18h,3 stops,"BOM, IDR, DEL",16:15+1,BLR,7 deals from,"₹ 15,246",Select,Air India
35,"Flight option 45: Total cost ₹ 15,309.",22:15,HYD,18h,2 stops,"BOM, DEL",16:15+1,BLR,2 deals from,"₹ 15,309",Select,Air India
36,"Flight option 46: Total cost ₹ 13,322.",20:40,HYD,21h 40,2 stops,"DEL, BOM",18:20+1,BLR,8 deals from,"₹ 13,322",Select,Air India
37,"Flight option 48: Total cost ₹ 14,907.",13:30,HYD,19h 25,2 stops,"BBI, DEL",08:55+1,BLR,8 deals from,"₹ 14,907",Select,Air India
38,"Flight option 49: Total cost ₹ 15,772.",16:10,HYD,19h,2 stops,"DEL, BOM",11:10+1,BLR,4 deals from,"₹ 15,772",Select,Air India
39,"Flight option 50: Total cost ₹ 17,220.",13:25,HYD,18h 25,2 stops,"DEL, BOM",07:50+1,BLR,3 deals from,"₹ 17,220",Select,Vistara
40,"Flight option 51: Total cost ₹ 17,334.",12:55,HYD,20h 05,2 stops,"BOM, DEL",09:00+1,BLR,5 deals from,"₹ 17,334",Select,Vistara
41,"Flight option 53: Total cost ₹ 59,711.",10:05,HYD,6h 10,1 stop,DEL,16:15,BLR,1 deal,"₹ 59,711",Select,Air India
42,"Flight option 54: Total cost ₹ 54,424.",13:25,HYD,7h,1 stop,DEL,20:25,BLR,4 deals from,"₹ 54,424",Select,Vistara
43,"Flight option 55: Total cost ₹ 19,406.",17:40,HYD,24h 05,2 stops,"DEL, BOM",17:45+1,BLR,3 deals from,"₹ 19,406",Select,Vistara
44,"Flight option 56: Total cost ₹ 57,060.",10:10,HYD,8h 40,1 stop,DEL,18:50,BLR,1 deal,"₹ 57,060",Select,Vistara
45,"Flight option 57: Total cost ₹ 22,069.",21:20,HYD,22h 50,1 stop,CMB,20:10+1,BLR,3 deals from,"₹ 22,069",Select,SriLankan Airlines
46,"Flight option 58: Total cost ₹ 58,890.",11:35,HYD,8h 50,2 stops,"IXC, DEL",20:25,BLR,2 deals from,"₹ 58,890",Select,Vistara

## Manually select fro diffeernt dates with 10 days differences

### As there was a issue getting the data and the scapping is detected as scam, So collected the url and extracted the data

In [37]:
## changed the dates in url and extracted the data

driver=webdriver.Chrome(r'C:\Users\surendar.reddy\Documents\data Science projet_Data traine\chromedriver.exe')
time.sleep(3)
url ="https://www.skyscanner.co.in/transport/flights/hyd/blr/220507/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&priceSourceId=&priceTrace=&qp_prevCurrency=INR&qp_prevPrice=OneWayNone&qp_prevProvider=ins_month&rtn=0"
driver.get(url)

In [41]:
HYD_BAN_7May = []
HYD_BAN_7May_AIRLINES = []
for i in driver.find_elements_by_xpath('//div[@class="FlightsTicket_container__NWJkY"]'):
     HYD_BAN_7May.append(i.text.split('\n'))       
for i in driver.find_elements_by_xpath("//div[@class='BpkImage_bpk-image__NzYwO BpkImage_bpk-image--no-background__OTRiM']//img") :
     HYD_BAN_7May_AIRLINES.append(i.get_attribute('alt'))

# slicing odd
HYD_BAN_7May_AIRLINES  = HYD_BAN_7May_AIRLINES[::2]

#changing to dataframe
df_HYD_BAN_7May=pd.DataFrame(HYD_BAN_7May)
df_HYD_BAN_7May_AIRLINES=pd.DataFrame(HYD_BAN_7May_AIRLINES)

#join the 2 data Frame
df_HYD_BAN_7May = df_HYD_BAN_7May.join(df_HYD_BAN_7May_AIRLINES,how = 'right', lsuffix='_x')
#merged = df_train_csv.join(df_train_fly, how = 'right', lsuffix='_x')

#writing in Excel
writer=pd.ExcelWriter("df_HYD_BAN_7May.xlsx")
df_HYD_BAN_7May.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_BAN_7May

,0_x,1,2,3,4,5,6,7,8,9,10,11,0
0,"Flight option 1: Total cost ₹ 3,750.",18:25,HYD,1h 05,Direct,19:30,BLR,19 deals from,"₹ 3,750",Select,None,None,Vistara
1,"Flight option 2: Total cost ₹ 3,560.",22:30,HYD,1h 10,Direct,23:40,BLR,20 deals from,"₹ 3,560",Select,None,None,IndiGo
2,"Flight option 3: Total cost ₹ 3,560.",23:40,HYD,1h 10,Direct,00:50+1,BLR,20 deals from,"₹ 3,560",Select,None,None,IndiGo
3,"Flight option 5: Total cost ₹ 3,560.",07:00,HYD,1h 15,Direct,08:15,BLR,20 deals from,"₹ 3,560",Select,None,None,IndiGo
4,"Flight option 6: Total cost ₹ 3,750.",07:30,HYD,1h 15,Direct,08:45,BLR,19 deals from,"₹ 3,750",Select,None,None,Vistara
...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,"Flight option 103: Total cost ₹ 36,706.",06:10,HYD,16h 20,1 stop,DEL,22:30,BLR,4 deals from,"₹ 36,706",Select,None,Hahn Air Systems
84,"Flight option 104: Total cost ₹ 53,853.",19:10,HYD,13h 45,2 stops,"GOI, DEL",08:55+1,BLR,Partly operated by SpiceJet,2 deals from,"₹ 53,853",Select,Emirates
85,"Flight option 105: Total cost ₹ 82,084.",21:50,HYD,11h 05,1 stop,DXB,08:55+1,BLR,1 deal,"₹ 82,084",Select,None,Hahn Air Systems
86,"Flight option 106: Total cost ₹ 52,514.",06:10,HYD,17h 45,2 stops,"DEL, GOI",23:55,BLR,Partly operated by SpiceJet,2 deals from,"₹ 52,514",Select,Hahn Air Systems
87,"Flight option 107: Total cost ₹ 36,414.",16:40,HYD,28h 20,1 stop,JRG,21:00+1,BLR,1 deal,"₹ 36,414",Select,None,Emirates

In [43]:
## changed the dates in url and extracted the data

driver=webdriver.Chrome(r'C:\Users\surendar.reddy\Documents\data Science projet_Data traine\chromedriver.exe')
time.sleep(3)
url ="https://www.skyscanner.co.in/transport/flights/hyd/blr/220517/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&priceSourceId=&priceTrace=&qp_prevCurrency=INR&qp_prevPrice=OneWayNone&qp_prevProvider=ins_month&rtn=0"
driver.get(url)

In [44]:
HYD_BAN_17May = []
HYD_BAN_17May_AIRLINES = []
for i in driver.find_elements_by_xpath('//div[@class="FlightsTicket_container__NWJkY"]'):
     HYD_BAN_17May.append(i.text.split('\n'))       
for i in driver.find_elements_by_xpath("//div[@class='BpkImage_bpk-image__NzYwO BpkImage_bpk-image--no-background__OTRiM']//img") :
     HYD_BAN_17May_AIRLINES.append(i.get_attribute('alt'))

# slicing odd
HYD_BAN_17May_AIRLINES  = HYD_BAN_17May_AIRLINES[::2]

#changing to dataframe
df_HYD_BAN_17May=pd.DataFrame(HYD_BAN_17May)
df_HYD_BAN_17May_AIRLINES=pd.DataFrame(HYD_BAN_17May_AIRLINES)

#join the 2 data Frame
df_HYD_BAN_17May = df_HYD_BAN_17May.join(df_HYD_BAN_17May_AIRLINES,how = 'right', lsuffix='_x')
#merged = df_train_csv.join(df_train_fly, how = 'right', lsuffix='_x')

#writing in Excel
writer=pd.ExcelWriter("df_HYD_BAN_17May.xlsx")
df_HYD_BAN_17May.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_BAN_17May

,0_x,1,2,3,4,5,6,7,8,9,10,11,0
0,"Flight option 1: Total cost ₹ 3,944.",18:25,HYD,1h 05,Direct,19:30,BLR,18 deals from,"₹ 3,944",Select,None,None,Vistara
1,"Flight option 2: Total cost ₹ 4,206.",16:50,HYD,1h 05,Direct,17:55,BLR,18 deals from,"₹ 4,206",Select,None,None,Air India
2,"Flight option 3: Total cost ₹ 4,159.",09:30,HYD,1h 05,Direct,10:35,BLR,19 deals from,"₹ 4,159",Select,None,None,IndiGo
3,"Flight option 5: Total cost ₹ 3,967.",14:20,HYD,1h 10,Direct,15:30,BLR,16 deals from,"₹ 3,967",Select,None,None,AirAsia India
4,"Flight option 6: Total cost ₹ 3,273.",Alliance Air,20:45,HYD,1h 30,Direct,22:15,BLR,4 deals from,"₹ 3,273",Select,None,IndiGo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,"Flight option 96: Total cost ₹ 36,680.",06:10,HYD,16h 20,1 stop,DEL,22:30,BLR,Operated by SpiceJet,4 deals from,"₹ 36,680",Select,Hahn Air Systems
78,"Flight option 97: Total cost ₹ 34,296.",12:25,HYD,20h,1 stop,CCU,08:25+1,BLR,Operated by SpiceJet,3 deals from,"₹ 34,296",Select,Hahn Air Systems
79,"Flight option 98: Total cost ₹ 53,836.",19:10,HYD,13h 45,2 stops,"GOI, DEL",08:55+1,BLR,Operated by SpiceJet,3 deals from,"₹ 53,836",Select,Hahn Air Systems
80,"Flight option 99: Total cost ₹ 53,836.",06:00,HYD,16h 30,2 stops,"GOI, DEL",22:30,BLR,Operated by SpiceJet,3 deals from,"₹ 53,836",Select,Hahn Air Systems
81,"Flight option 100: Total cost ₹ 52,488.",06:10,HYD,17h 45,2 stops,"DEL, GOI",23:55,BLR,Operated by SpiceJet,2 deals from,"₹ 52,488",Select,Hahn Air Systems

In [45]:
driver=webdriver.Chrome(r'C:\Users\surendar.reddy\Documents\data Science projet_Data traine\chromedriver.exe')
time.sleep(3)
url ="https://www.skyscanner.co.in/transport/flights/hyd/blr/220527/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&priceSourceId=&priceTrace=&qp_prevCurrency=INR&qp_prevPrice=OneWayNone&qp_prevProvider=ins_month&rtn=0"
driver.get(url)

In [46]:
HYD_BAN_27May = []
HYD_BAN_27May_AIRLINES = []
for i in driver.find_elements_by_xpath('//div[@class="FlightsTicket_container__NWJkY"]'):
     HYD_BAN_27May.append(i.text.split('\n'))       
for i in driver.find_elements_by_xpath("//div[@class='BpkImage_bpk-image__NzYwO BpkImage_bpk-image--no-background__OTRiM']//img") :
     HYD_BAN_27May_AIRLINES.append(i.get_attribute('alt'))

# slicing odd
HYD_BAN_27May_AIRLINES  = HYD_BAN_27May_AIRLINES[::2]

#changing to dataframe
df_HYD_BAN_27May=pd.DataFrame(HYD_BAN_27May)
df_HYD_BAN_27May_AIRLINES=pd.DataFrame(HYD_BAN_27May_AIRLINES)

#join the 2 data Frame
df_HYD_BAN_27May = df_HYD_BAN_27May.join(df_HYD_BAN_27May_AIRLINES,how = 'right', lsuffix='_x')
#merged = df_train_csv.join(df_train_fly, how = 'right', lsuffix='_x')

#writing in Excel
writer=pd.ExcelWriter("df_HYD_BAN_27May.xlsx")
df_HYD_BAN_27May.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_BAN_27May

,0_x,1,2,3,4,5,6,7,8,9,10,11,0
0,"Flight option 1: Total cost ₹ 3,551.",18:25,HYD,1h 05,Direct,19:30,BLR,19 deals from,"₹ 3,551",Select,None,None,Vistara
1,"Flight option 2: Total cost ₹ 3,637.",09:30,HYD,1h 05,Direct,10:35,BLR,20 deals from,"₹ 3,637",Select,None,None,IndiGo
2,"Flight option 3: Total cost ₹ 3,551.",07:30,HYD,1h 15,Direct,08:45,BLR,19 deals from,"₹ 3,551",Select,None,None,Vistara
3,"Flight option 5: Total cost ₹ 3,623.",12:00,HYD,1h 10,Direct,13:10,BLR,20 deals from,"₹ 3,623",Select,None,None,IndiGo
4,"Flight option 6: Total cost ₹ 3,623.",08:15,HYD,1h 15,Direct,09:30,BLR,20 deals from,"₹ 3,623",Select,None,None,IndiGo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,"Flight option 100: Total cost ₹ 34,412.",06:15,HYD,13h 10,1 stop,JLR,19:25,BLR,6 deals from,"₹ 34,412",Select,None,Hahn Air Systems
81,"Flight option 101: Total cost ₹ 35,564.",06:10,HYD,16h 20,1 stop,DEL,22:30,BLR,4 deals from,"₹ 35,564",Select,None,Hahn Air Systems
82,"Flight option 102: Total cost ₹ 51,590.",19:10,HYD,13h 45,2 stops,"GOI, DEL",08:55+1,BLR,Partly operated by SpiceJet,2 deals from,"₹ 51,590",Select,Malaysia Airlines
83,"Flight option 103: Total cost ₹ 36,334.",00:15,HYD,23h 25,1 stop,KUL,23:40,BLR,2 deals from,"₹ 36,334",Select,None,Hahn Air Systems
84,"Flight option 104: Total cost ₹ 50,955.",06:10,HYD,17h 15,2 stops,"DEL, GOI",23:25,BLR,Partly operated by SpiceJet,2 deals from,"₹ 50,955",Select,Hahn Air Systems

In [48]:
driver=webdriver.Chrome(r'C:\Users\surendar.reddy\Documents\data Science projet_Data traine\chromedriver.exe')
time.sleep(3)
url ="https://www.skyscanner.co.in/transport/flights/hyd/blr/220607/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&priceSourceId=&priceTrace=&qp_prevCurrency=INR&qp_prevPrice=OneWayNone&qp_prevProvider=ins_month&rtn=0"
driver.get(url)

In [49]:
HYD_BAN_7June = []
HYD_BAN_7June_AIRLINES = []
for i in driver.find_elements_by_xpath('//div[@class="FlightsTicket_container__NWJkY"]'):
     HYD_BAN_7June.append(i.text.split('\n'))       
for i in driver.find_elements_by_xpath("//div[@class='BpkImage_bpk-image__NzYwO BpkImage_bpk-image--no-background__OTRiM']//img") :
     HYD_BAN_7June_AIRLINES.append(i.get_attribute('alt'))

# slicing odd
HYD_BAN_7June_AIRLINES  = HYD_BAN_7June_AIRLINES[::2]

#changing to dataframe
df_HYD_BAN_7June=pd.DataFrame(HYD_BAN_7June)
df_HYD_BAN_7June_AIRLINES=pd.DataFrame(HYD_BAN_7June_AIRLINES)

#join the 2 data Frame
df_HYD_BAN_7June = df_HYD_BAN_7June.join(df_HYD_BAN_7June_AIRLINES,how = 'right', lsuffix='_x')
#merged = df_train_csv.join(df_train_fly, how = 'right', lsuffix='_x')

#writing in Excel
writer=pd.ExcelWriter("df_HYD_BAN_7June.xlsx")
df_HYD_BAN_7June.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_BAN_7June

,0_x,1,2,3,4,5,6,7,8,9,10,11,0
0,"Flight option 1: Total cost ₹ 3,551.",18:25,HYD,1h 05,Direct,19:30,BLR,18 deals from,"₹ 3,551",Select,None,None,Vistara
1,"Flight option 2: Total cost ₹ 3,623.",09:30,HYD,1h 05,Direct,10:35,BLR,19 deals from,"₹ 3,623",Select,None,None,IndiGo
2,"Flight option 3: Total cost ₹ 3,623.",20:30,HYD,1h 05,Direct,21:35,BLR,19 deals from,"₹ 3,623",Select,None,None,IndiGo
3,"Flight option 5: Total cost ₹ 3,623.",18:10,HYD,1h 10,Direct,19:20,BLR,19 deals from,"₹ 3,623",Select,None,None,IndiGo
4,"Flight option 6: Total cost ₹ 3,623.",12:00,HYD,1h 10,Direct,13:10,BLR,19 deals from,"₹ 3,623",Select,None,None,IndiGo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,"Flight option 94: Total cost ₹ 12,653.",16:10,HYD,32h 10,2 stops,"DEL, LKO",00:20+2,BLR,2 deals from,"₹ 12,653",Select,None,Hahn Air Systems
76,"Flight option 95: Total cost ₹ 34,412.",06:15,HYD,13h 10,1 stop,JLR,19:25,BLR,Operated by SpiceJet,5 deals from,"₹ 34,412",Select,Hahn Air Systems
77,"Flight option 96: Total cost ₹ 35,564.",06:10,HYD,16h 20,1 stop,DEL,22:30,BLR,Operated by SpiceJet,4 deals from,"₹ 35,564",Select,Hahn Air Systems
78,"Flight option 97: Total cost ₹ 51,590.",19:10,HYD,13h 45,2 stops,"GOI, DEL",08:55+1,BLR,Operated by SpiceJet,3 deals from,"₹ 51,590",Select,Hahn Air Systems
79,"Flight option 98: Total cost ₹ 50,955.",06:10,HYD,17h 15,2 stops,"DEL, GOI",23:25,BLR,Operated by SpiceJet,2 deals from,"₹ 50,955",Select,Hahn Air Systems

In [51]:
driver=webdriver.Chrome(r'C:\Users\surendar.reddy\Documents\data Science projet_Data traine\chromedriver.exe')
time.sleep(3)
url ="https://www.skyscanner.co.in/transport/flights/hyd/blr/220617/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&priceSourceId=&priceTrace=&qp_prevCurrency=INR&qp_prevPrice=OneWayNone&qp_prevProvider=ins_month&rtn=0"
driver.get(url)

In [52]:
HYD_BAN_17June = []
HYD_BAN_17June_AIRLINES = []
for i in driver.find_elements_by_xpath('//div[@class="FlightsTicket_container__NWJkY"]'):
     HYD_BAN_17June.append(i.text.split('\n'))       
for i in driver.find_elements_by_xpath("//div[@class='BpkImage_bpk-image__NzYwO BpkImage_bpk-image--no-background__OTRiM']//img") :
     HYD_BAN_17June_AIRLINES.append(i.get_attribute('alt'))

# slicing odd
HYD_BAN_17June_AIRLINES  = HYD_BAN_17June_AIRLINES[::2]

#changing to dataframe
df_HYD_BAN_17June=pd.DataFrame(HYD_BAN_17June)
df_HYD_BAN_17June_AIRLINES=pd.DataFrame(HYD_BAN_17June_AIRLINES)

#join the 2 data Frame
df_HYD_BAN_17June = df_HYD_BAN_17June.join(df_HYD_BAN_17June_AIRLINES,how = 'right', lsuffix='_x')
#merged = df_train_csv.join(df_train_fly, how = 'right', lsuffix='_x')

#writing in Excel
writer=pd.ExcelWriter("df_HYD_BAN_17June.xlsx")
df_HYD_BAN_17June.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_BAN_17June

,0_x,1,2,3,4,5,6,7,8,9,10,11,0
0,"Flight option 1: Total cost ₹ 3,551.",18:25,HYD,1h 05,Direct,19:30,BLR,17 deals from,"₹ 3,551",Select,None,None,Vistara
1,"Flight option 2: Total cost ₹ 3,837.",09:30,HYD,1h 05,Direct,10:35,BLR,18 deals from,"₹ 3,837",Select,None,None,IndiGo
2,"Flight option 3: Total cost ₹ 3,551.",07:30,HYD,1h 15,Direct,08:45,BLR,17 deals from,"₹ 3,551",Select,None,None,Vistara
3,"Flight option 5: Total cost ₹ 3,837.",20:30,HYD,1h 05,Direct,21:35,BLR,18 deals from,"₹ 3,837",Select,None,None,IndiGo
4,"Flight option 6: Total cost ₹ 3,744.",14:20,HYD,1h 10,Direct,15:30,BLR,15 deals from,"₹ 3,744",Select,None,None,AirAsia India
...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,"Flight option 92: Total cost ₹ 35,559.",06:10,HYD,16h 20,1 stop,DEL,22:30,BLR,Operated by SpiceJet,4 deals from,"₹ 35,559",Select,Hahn Air Systems
75,"Flight option 93: Total cost ₹ 29,937.",00:15,HYD,23h 25,1 stop,KUL,23:40,BLR,2 deals from,"₹ 29,937",Select,None,Malaysia Airlines
76,"Flight option 94: Total cost ₹ 51,590.",19:10,HYD,13h 45,2 stops,"GOI, DEL",08:55+1,BLR,Operated by SpiceJet,3 deals from,"₹ 51,590",Select,Hahn Air Systems
77,"Flight option 95: Total cost ₹ 51,590.",06:00,HYD,16h 30,2 stops,"GOI, DEL",22:30,BLR,Operated by SpiceJet,3 deals from,"₹ 51,590",Select,Hahn Air Systems
78,"Flight option 96: Total cost ₹ 50,955.",06:10,HYD,17h 15,2 stops,"DEL, GOI",23:25,BLR,Operated by SpiceJet,2 deals from,"₹ 50,955",Select,Hahn Air Systems

In [53]:
driver=webdriver.Chrome(r'C:\Users\surendar.reddy\Documents\data Science projet_Data traine\chromedriver.exe')
time.sleep(3)
url ="https://www.skyscanner.co.in/transport/flights/hyd/blr/220627/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&priceSourceId=&priceTrace=&qp_prevCurrency=INR&qp_prevPrice=OneWayNone&qp_prevProvider=ins_month&rtn=0"
driver.get(url)

In [54]:
HYD_BAN_27June = []
HYD_BAN_27June_AIRLINES = []
for i in driver.find_elements_by_xpath('//div[@class="FlightsTicket_container__NWJkY"]'):
     HYD_BAN_27June.append(i.text.split('\n'))       
for i in driver.find_elements_by_xpath("//div[@class='BpkImage_bpk-image__NzYwO BpkImage_bpk-image--no-background__OTRiM']//img") :
     HYD_BAN_27June_AIRLINES.append(i.get_attribute('alt'))

# slicing odd
HYD_BAN_27June_AIRLINES  = HYD_BAN_27June_AIRLINES[::2]

#changing to dataframe
df_HYD_BAN_27June=pd.DataFrame(HYD_BAN_27June)
df_HYD_BAN_27June_AIRLINES=pd.DataFrame(HYD_BAN_27June_AIRLINES)

#join the 2 data Frame
df_HYD_BAN_27June = df_HYD_BAN_27June.join(df_HYD_BAN_27June_AIRLINES,how = 'right', lsuffix='_x')
#merged = df_train_csv.join(df_train_fly, how = 'right', lsuffix='_x')

#writing in Excel
writer=pd.ExcelWriter("df_HYD_BAN_27June.xlsx")
df_HYD_BAN_27June.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_BAN_27June

,0_x,1,2,3,4,5,6,7,8,9,10,11,0
0,"Flight option 1: Total cost ₹ 3,230.",18:25,HYD,1h 05,Direct,19:30,BLR,18 deals from,"₹ 3,230",Select,None,None,Vistara
1,"Flight option 2: Total cost ₹ 3,352.",21:10,HYD,1h 05,Direct,22:15,BLR,16 deals from,"₹ 3,352",Select,None,None,AirAsia India
2,"Flight option 3: Total cost ₹ 3,352.",14:20,HYD,1h 10,Direct,15:30,BLR,16 deals from,"₹ 3,352",Select,None,None,AirAsia India
3,"Flight option 5: Total cost ₹ 3,230.",07:30,HYD,1h 15,Direct,08:45,BLR,18 deals from,"₹ 3,230",Select,None,None,Vistara
4,"Flight option 6: Total cost ₹ 3,681.",12:00,HYD,1h 15,Direct,13:15,BLR,18 deals from,"₹ 3,681",Select,None,None,Air India
...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,"Flight option 89: Total cost ₹ 21,998.",21:20,HYD,22h 50,1 stop,CMB,20:10+1,BLR,3 deals from,"₹ 21,998",Select,None,Hahn Air Systems
72,"Flight option 90: Total cost ₹ 35,555.",06:10,HYD,16h 20,1 stop,DEL,22:30,BLR,Operated by SpiceJet,4 deals from,"₹ 35,555",Select,Hahn Air Systems
73,"Flight option 91: Total cost ₹ 51,587.",19:10,HYD,13h 45,2 stops,"GOI, DEL",08:55+1,BLR,Operated by SpiceJet,3 deals from,"₹ 51,587",Select,Hahn Air Systems
74,"Flight option 92: Total cost ₹ 51,587.",06:00,HYD,16h 30,2 stops,"GOI, DEL",22:30,BLR,Operated by SpiceJet,3 deals from,"₹ 51,587",Select,Hahn Air Systems
75,"Flight option 93: Total cost ₹ 50,953.",06:10,HYD,17h 15,2 stops,"DEL, GOI",23:25,BLR,Operated by SpiceJet,2 deals from,"₹ 50,953",Select,Hahn Air Systems

In [56]:
driver=webdriver.Chrome(r'C:\Users\surendar.reddy\Documents\data Science projet_Data traine\chromedriver.exe')
time.sleep(3)
url ="https://www.skyscanner.co.in/transport/flights/hyd/blr/220707/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&priceSourceId=&priceTrace=&qp_prevCurrency=INR&qp_prevPrice=OneWayNone&qp_prevProvider=ins_month&rtn=0"
driver.get(url)

In [57]:
HYD_BAN_7July = []
HYD_BAN_7July_AIRLINES = []
for i in driver.find_elements_by_xpath('//div[@class="FlightsTicket_container__NWJkY"]'):
     HYD_BAN_7July.append(i.text.split('\n'))       
for i in driver.find_elements_by_xpath("//div[@class='BpkImage_bpk-image__NzYwO BpkImage_bpk-image--no-background__OTRiM']//img") :
     HYD_BAN_7July_AIRLINES.append(i.get_attribute('alt'))

# slicing odd
HYD_BAN_7July_AIRLINES  = HYD_BAN_7July_AIRLINES[::2]

#changing to dataframe
df_HYD_BAN_7July=pd.DataFrame(HYD_BAN_7July)
df_HYD_BAN_7July_AIRLINES=pd.DataFrame(HYD_BAN_7July_AIRLINES)

#join the 2 data Frame
df_HYD_BAN_7July = df_HYD_BAN_7July.join(df_HYD_BAN_7July_AIRLINES,how = 'right', lsuffix='_x')
#merged = df_train_csv.join(df_train_fly, how = 'right', lsuffix='_x')

#writing in Excel
writer=pd.ExcelWriter("df_HYD_BAN_7July.xlsx")
df_HYD_BAN_7July.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_BAN_7July

,0_x,1,2,3,4,5,6,7,8,9,10,11,0
0,"Flight option 1: Total cost ₹ 3,230.",18:25,HYD,1h 05,Direct,19:30,BLR,18 deals from,"₹ 3,230",Select,None,None,Vistara
1,"Flight option 2: Total cost ₹ 3,200.",06:00,HYD,1h 05,Direct,07:05,BLR,14 deals from,"₹ 3,200",Select,None,None,GoAir
2,"Flight option 3: Total cost ₹ 3,230.",07:30,HYD,1h 15,Direct,08:45,BLR,18 deals from,"₹ 3,230",Select,None,None,Vistara
3,"Flight option 5: Total cost ₹ 3,352.",14:20,HYD,1h 10,Direct,15:30,BLR,16 deals from,"₹ 3,352",Select,None,None,AirAsia India
4,"Flight option 6: Total cost ₹ 3,623.",09:30,HYD,1h 05,Direct,10:35,BLR,19 deals from,"₹ 3,623",Select,None,None,IndiGo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,"Flight option 100: Total cost ₹ 34,677.",06:15,HYD,13h 10,1 stop,JLR,19:25,BLR,Operated by SpiceJet,6 deals from,"₹ 34,677",Select,Hahn Air Systems
81,"Flight option 101: Total cost ₹ 35,457.",06:10,HYD,16h 20,1 stop,DEL,22:30,BLR,Operated by SpiceJet,4 deals from,"₹ 35,457",Select,Hahn Air Systems
82,"Flight option 102: Total cost ₹ 51,581.",19:10,HYD,13h 45,2 stops,"GOI, DEL",08:55+1,BLR,Operated by SpiceJet,3 deals from,"₹ 51,581",Select,Hahn Air Systems
83,"Flight option 103: Total cost ₹ 51,581.",06:00,HYD,16h 30,2 stops,"GOI, DEL",22:30,BLR,Operated by SpiceJet,3 deals from,"₹ 51,581",Select,Hahn Air Systems
84,"Flight option 104: Total cost ₹ 50,946.",06:10,HYD,17h 15,2 stops,"DEL, GOI",23:25,BLR,Operated by SpiceJet,2 deals from,"₹ 50,946",Select,Hahn Air Systems

In [62]:
driver=webdriver.Chrome(r'C:\Users\surendar.reddy\Documents\data Science projet_Data traine\chromedriver.exe')
time.sleep(10)
url ="https://www.skyscanner.co.in/transport/flights/hyd/blr/220717/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&priceSourceId=&priceTrace=&qp_prevCurrency=INR&qp_prevPrice=OneWayNone&qp_prevProvider=ins_month&rtn=0"
driver.get(url)

In [63]:
HYD_BAN_17July = []
HYD_BAN_17July_AIRLINES = []
for i in driver.find_elements_by_xpath('//div[@class="FlightsTicket_container__NWJkY"]'):
     HYD_BAN_17July.append(i.text.split('\n'))       
for i in driver.find_elements_by_xpath("//div[@class='BpkImage_bpk-image__NzYwO BpkImage_bpk-image--no-background__OTRiM']//img") :
     HYD_BAN_17July_AIRLINES.append(i.get_attribute('alt'))

# slicing odd
HYD_BAN_17July_AIRLINES  = HYD_BAN_17July_AIRLINES[::2]

#changing to dataframe
df_HYD_BAN_17July=pd.DataFrame(HYD_BAN_17July)
df_HYD_BAN_17July_AIRLINES=pd.DataFrame(HYD_BAN_17July_AIRLINES)

#join the 2 data Frame
df_HYD_BAN_17July = df_HYD_BAN_17July.join(df_HYD_BAN_17July_AIRLINES,how = 'right', lsuffix='_x')
#merged = df_train_csv.join(df_train_fly, how = 'right', lsuffix='_x')

#writing in Excel
writer=pd.ExcelWriter("df_HYD_BAN_17July.xlsx")
df_HYD_BAN_17July.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_BAN_17July

,0_x,1,2,3,4,5,6,7,8,9,10,11,0
0,"Flight option 1: Total cost ₹ 3,200.",06:00,HYD,1h 05,Direct,07:05,BLR,14 deals from,"₹ 3,200",Select,None,None,GoAir
1,"Flight option 2: Total cost ₹ 3,230.",18:25,HYD,1h 05,Direct,19:30,BLR,17 deals from,"₹ 3,230",Select,None,None,Vistara
2,"Flight option 3: Total cost ₹ 3,351.",23:40,HYD,1h 10,Direct,00:50+1,BLR,18 deals from,"₹ 3,351",Select,None,None,IndiGo
3,"Flight option 5: Total cost ₹ 3,351.",22:30,HYD,1h 10,Direct,23:40,BLR,18 deals from,"₹ 3,351",Select,None,None,IndiGo
4,"Flight option 6: Total cost ₹ 3,623.",09:30,HYD,1h 05,Direct,10:35,BLR,18 deals from,"₹ 3,623",Select,None,None,IndiGo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,"Flight option 96: Total cost ₹ 17,278.",20:30,HYD,25h 20,2 stops,"DEL, IDR",21:50+1,BLR,1 deal,"₹ 17,278",Select,None,Hahn Air Systems
78,"Flight option 97: Total cost ₹ 34,675.",06:15,HYD,13h 10,1 stop,JLR,19:25,BLR,Operated by SpiceJet,5 deals from,"₹ 34,675",Select,Hahn Air Systems
79,"Flight option 98: Total cost ₹ 35,456.",06:10,HYD,16h 20,1 stop,DEL,22:30,BLR,Operated by SpiceJet,4 deals from,"₹ 35,456",Select,Hahn Air Systems
80,"Flight option 99: Total cost ₹ 51,576.",19:10,HYD,13h 45,2 stops,"GOI, DEL",08:55+1,BLR,Operated by SpiceJet,3 deals from,"₹ 51,576",Select,Hahn Air Systems
81,"Flight option 100: Total cost ₹ 51,580.",06:00,HYD,16h 30,2 stops,"GOI, DEL",22:30,BLR,Operated by SpiceJet,3 deals from,"₹ 51,580",Select,Hahn Air Systems

In [66]:
driver=webdriver.Chrome(r'C:\Users\surendar.reddy\Documents\data Science projet_Data traine\chromedriver.exe')
time.sleep(2)
url ="https://www.skyscanner.co.in/transport/flights/hyd/blr/220727/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&priceSourceId=&priceTrace=&qp_prevCurrency=INR&qp_prevPrice=OneWayNone&qp_prevProvider=ins_month&rtn=0"
driver.get(url)

In [67]:
HYD_BAN_27July = []
HYD_BAN_27July_AIRLINES = []
for i in driver.find_elements_by_xpath('//div[@class="FlightsTicket_container__NWJkY"]'):
     HYD_BAN_27July.append(i.text.split('\n'))       
for i in driver.find_elements_by_xpath("//div[@class='BpkImage_bpk-image__NzYwO BpkImage_bpk-image--no-background__OTRiM']//img") :
     HYD_BAN_27July_AIRLINES.append(i.get_attribute('alt'))

# slicing odd
HYD_BAN_27July_AIRLINES  = HYD_BAN_27July_AIRLINES[::2]

#changing to dataframe
df_HYD_BAN_27July=pd.DataFrame(HYD_BAN_27July)
df_HYD_BAN_27July_AIRLINES=pd.DataFrame(HYD_BAN_27July_AIRLINES)

#join the 2 data Frame
df_HYD_BAN_27July = df_HYD_BAN_27July.join(df_HYD_BAN_27July_AIRLINES,how = 'right', lsuffix='_x')
#merged = df_train_csv.join(df_train_fly, how = 'right', lsuffix='_x')

#writing in Excel
writer=pd.ExcelWriter("df_HYD_BAN_27July.xlsx")
df_HYD_BAN_27July.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_BAN_27July

,0_x,1,2,3,4,5,6,7,8,9,10,11,0
0,"Flight option 1: Total cost ₹ 3,532.",06:00,HYD,1h 05,Direct,07:05,BLR,15 deals from,"₹ 3,532",Select,None,None,GoAir
1,"Flight option 2: Total cost ₹ 3,551.",18:25,HYD,1h 05,Direct,19:30,BLR,18 deals from,"₹ 3,551",Select,None,None,Vistara
2,"Flight option 3: Total cost ₹ 3,623.",09:30,HYD,1h 05,Direct,10:35,BLR,20 deals from,"₹ 3,623",Select,None,None,IndiGo
3,"Flight option 5: Total cost ₹ 3,623.",20:30,HYD,1h 05,Direct,21:35,BLR,20 deals from,"₹ 3,623",Select,None,None,IndiGo
4,"Flight option 6: Total cost ₹ 3,623.",12:00,HYD,1h 10,Direct,13:10,BLR,20 deals from,"₹ 3,623",Select,None,None,IndiGo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,"Flight option 92: Total cost ₹ 34,573.",06:15,HYD,13h 10,1 stop,JLR,19:25,BLR,6 deals from,"₹ 34,573",Select,None,Hahn Air Systems
75,"Flight option 93: Total cost ₹ 35,443.",06:10,HYD,16h 20,1 stop,DEL,22:30,BLR,4 deals from,"₹ 35,443",Select,None,Hahn Air Systems
76,"Flight option 94: Total cost ₹ 51,567.",19:10,HYD,13h 45,2 stops,"GOI, DEL",08:55+1,BLR,Partly operated by SpiceJet,3 deals from,"₹ 51,567",Select,Hahn Air Systems
77,"Flight option 95: Total cost ₹ 51,567.",06:00,HYD,16h 30,2 stops,"GOI, DEL",22:30,BLR,Partly operated by SpiceJet,3 deals from,"₹ 51,567",Select,Hahn Air Systems
78,"Flight option 96: Total cost ₹ 50,932.",06:10,HYD,17h 15,2 stops,"DEL, GOI",23:25,BLR,4 deals from,"₹ 50,932",Select,None,Hahn Air Systems

In [69]:
driver=webdriver.Chrome(r'C:\Users\surendar.reddy\Documents\data Science projet_Data traine\chromedriver.exe')
time.sleep(2)
url ="https://www.skyscanner.co.in/transport/flights/hyd/blr/220807/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&priceSourceId=&priceTrace=&qp_prevCurrency=INR&qp_prevPrice=OneWayNone&qp_prevProvider=ins_month&rtn=0"
driver.get(url)

In [70]:
HYD_BAN_7Aug = []
HYD_BAN_7Aug_AIRLINES = []
for i in driver.find_elements_by_xpath('//div[@class="FlightsTicket_container__NWJkY"]'):
     HYD_BAN_7Aug.append(i.text.split('\n'))       
for i in driver.find_elements_by_xpath("//div[@class='BpkImage_bpk-image__NzYwO BpkImage_bpk-image--no-background__OTRiM']//img") :
     HYD_BAN_7Aug_AIRLINES.append(i.get_attribute('alt'))

# slicing odd
HYD_BAN_7Aug_AIRLINES  = HYD_BAN_7Aug_AIRLINES[::2]

#changing to dataframe
df_HYD_BAN_7Aug=pd.DataFrame(HYD_BAN_7Aug)
df_HYD_BAN_7Aug_AIRLINES=pd.DataFrame(HYD_BAN_7Aug_AIRLINES)

#join the 2 data Frame
df_HYD_BAN_7Aug = df_HYD_BAN_7Aug.join(df_HYD_BAN_7Aug_AIRLINES,how = 'right', lsuffix='_x')
#merged = df_train_csv.join(df_train_fly, how = 'right', lsuffix='_x')

#writing in Excel
writer=pd.ExcelWriter("df_HYD_BAN_7Aug.xlsx")
df_HYD_BAN_7Aug.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_BAN_7Aug

,0_x,1,2,3,4,5,6,7,8,9,10,11,0
0,"Flight option 1: Total cost ₹ 3,350.",06:00,HYD,1h 05,Direct,07:05,BLR,14 deals from,"₹ 3,350",Select,None,None,GoAir
1,"Flight option 2: Total cost ₹ 3,551.",18:25,HYD,1h 05,Direct,19:30,BLR,18 deals from,"₹ 3,551",Select,None,None,Vistara
2,"Flight option 3: Total cost ₹ 3,551.",07:30,HYD,1h 15,Direct,08:45,BLR,18 deals from,"₹ 3,551",Select,None,None,Vistara
3,"Flight option 5: Total cost ₹ 3,837.",09:30,HYD,1h 05,Direct,10:35,BLR,19 deals from,"₹ 3,837",Select,None,None,IndiGo
4,"Flight option 6: Total cost ₹ 3,837.",20:30,HYD,1h 05,Direct,21:35,BLR,19 deals from,"₹ 3,837",Select,None,None,IndiGo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,"Flight option 97: Total cost ₹ 35,425.",06:15,HYD,13h 10,1 stop,JLR,19:25,BLR,4 deals from,"₹ 35,425",Select,None,Hahn Air Systems
79,"Flight option 98: Total cost ₹ 36,258.",06:10,HYD,16h 20,1 stop,DEL,22:30,BLR,2 deals from,"₹ 36,258",Select,None,Hahn Air Systems
80,"Flight option 99: Total cost ₹ 55,033.",19:10,HYD,13h 45,2 stops,"GOI, DEL",08:55+1,BLR,Partly operated by SpiceJet,1 deal,"₹ 55,033",Select,Hahn Air Systems
81,"Flight option 100: Total cost ₹ 51,474.",06:10,HYD,17h 15,2 stops,"DEL, GOI",23:25,BLR,2 deals from,"₹ 51,474",Select,None,Hahn Air Systems
82,"Flight option 101: Total cost ₹ 55,033.",06:00,HYD,16h 30,2 stops,"GOI, DEL",22:30,BLR,Partly operated by SpiceJet,1 deal,"₹ 55,033",Select,Hahn Air Systems

In [72]:
driver=webdriver.Chrome(r'C:\Users\surendar.reddy\Documents\data Science projet_Data traine\chromedriver.exe')
time.sleep(2)
url ="https://www.skyscanner.co.in/transport/flights/hyd/blr/220817/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&priceSourceId=&priceTrace=&qp_prevCurrency=INR&qp_prevPrice=OneWayNone&qp_prevProvider=ins_month&rtn=0"
driver.get(url)

In [73]:
HYD_BAN_17Aug = []
HYD_BAN_17Aug_AIRLINES = []
for i in driver.find_elements_by_xpath('//div[@class="FlightsTicket_container__NWJkY"]'):
     HYD_BAN_17Aug.append(i.text.split('\n'))       
for i in driver.find_elements_by_xpath("//div[@class='BpkImage_bpk-image__NzYwO BpkImage_bpk-image--no-background__OTRiM']//img") :
     HYD_BAN_17Aug_AIRLINES.append(i.get_attribute('alt'))

# slicing odd
HYD_BAN_17Aug_AIRLINES  = HYD_BAN_17Aug_AIRLINES[::2]

#changing to dataframe
df_HYD_BAN_17Aug=pd.DataFrame(HYD_BAN_17Aug)
df_HYD_BAN_17Aug_AIRLINES=pd.DataFrame(HYD_BAN_17Aug_AIRLINES)

#join the 2 data Frame
df_HYD_BAN_17Aug = df_HYD_BAN_17Aug.join(df_HYD_BAN_17Aug_AIRLINES,how = 'right', lsuffix='_x')
#merged = df_train_csv.join(df_train_fly, how = 'right', lsuffix='_x')

#writing in Excel
writer=pd.ExcelWriter("df_HYD_BAN_17Aug.xlsx")
df_HYD_BAN_17Aug.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_BAN_17Aug

,0_x,1,2,3,4,5,6,7,8,9,10,11,0
0,"Flight option 1: Total cost ₹ 3,350.",06:00,HYD,1h 05,Direct,07:05,BLR,13 deals from,"₹ 3,350",Select,None,None,GoAir
1,"Flight option 2: Total cost ₹ 3,551.",18:25,HYD,1h 05,Direct,19:30,BLR,17 deals from,"₹ 3,551",Select,None,None,Vistara
2,"Flight option 3: Total cost ₹ 3,551.",07:30,HYD,1h 15,Direct,08:45,BLR,17 deals from,"₹ 3,551",Select,None,None,Vistara
3,"Flight option 5: Total cost ₹ 3,837.",09:30,HYD,1h 05,Direct,10:35,BLR,18 deals from,"₹ 3,837",Select,None,None,IndiGo
4,"Flight option 6: Total cost ₹ 3,681.",12:00,HYD,1h 15,Direct,13:15,BLR,17 deals from,"₹ 3,681",Select,None,None,Air India
...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,"Flight option 97: Total cost ₹ 34,571.",06:15,HYD,13h 10,1 stop,JLR,19:25,BLR,Operated by SpiceJet,5 deals from,"₹ 34,571",Select,Hahn Air Systems
79,"Flight option 98: Total cost ₹ 35,441.",06:10,HYD,16h 20,1 stop,DEL,22:30,BLR,Operated by SpiceJet,4 deals from,"₹ 35,441",Select,Hahn Air Systems
80,"Flight option 99: Total cost ₹ 53,597.",19:10,HYD,13h 45,2 stops,"GOI, DEL",08:55+1,BLR,Operated by SpiceJet,3 deals from,"₹ 53,597",Select,Hahn Air Systems
81,"Flight option 100: Total cost ₹ 50,931.",06:10,HYD,17h 15,2 stops,"DEL, GOI",23:25,BLR,Operated by SpiceJet,4 deals from,"₹ 50,931",Select,Hahn Air Systems
82,"Flight option 101: Total cost ₹ 53,597.",06:00,HYD,16h 30,2 stops,"GOI, DEL",22:30,BLR,Operated by SpiceJet,3 deals from,"₹ 53,597",Select,Hahn Air Systems

In [76]:
driver=webdriver.Chrome(r'C:\Users\surendar.reddy\Documents\data Science projet_Data traine\chromedriver.exe')
time.sleep(2)
url ="https://www.skyscanner.co.in/transport/flights/hyd/blr/220827/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&priceSourceId=&priceTrace=&qp_prevCurrency=INR&qp_prevPrice=OneWayNone&qp_prevProvider=ins_month&rtn=0"
driver.get(url)

In [77]:
HYD_BAN_27Aug = []
HYD_BAN_27Aug_AIRLINES = []
for i in driver.find_elements_by_xpath('//div[@class="FlightsTicket_container__NWJkY"]'):
     HYD_BAN_27Aug.append(i.text.split('\n'))       
for i in driver.find_elements_by_xpath("//div[@class='BpkImage_bpk-image__NzYwO BpkImage_bpk-image--no-background__OTRiM']//img") :
     HYD_BAN_27Aug_AIRLINES.append(i.get_attribute('alt'))

# slicing odd
HYD_BAN_27Aug_AIRLINES  = HYD_BAN_27Aug_AIRLINES[::2]

#changing to dataframe
df_HYD_BAN_27Aug=pd.DataFrame(HYD_BAN_27Aug)
df_HYD_BAN_27Aug_AIRLINES=pd.DataFrame(HYD_BAN_27Aug_AIRLINES)

#join the 2 data Frame
df_HYD_BAN_27Aug = df_HYD_BAN_27Aug.join(df_HYD_BAN_27Aug_AIRLINES,how = 'right', lsuffix='_x')
#merged = df_train_csv.join(df_train_fly, how = 'right', lsuffix='_x')

#writing in Excel
writer=pd.ExcelWriter("df_HYD_BAN_27Aug.xlsx")
df_HYD_BAN_27Aug.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_BAN_27Aug

,0_x,1,2,3,4,5,6,7,8,9,10,11,0
0,"Flight option 1: Total cost ₹ 3,350.",06:00,HYD,1h 05,Direct,07:05,BLR,14 deals from,"₹ 3,350",Select,None,None,GoAir
1,"Flight option 2: Total cost ₹ 3,551.",18:25,HYD,1h 05,Direct,19:30,BLR,18 deals from,"₹ 3,551",Select,None,None,Vistara
2,"Flight option 3: Total cost ₹ 3,837.",09:30,HYD,1h 05,Direct,10:35,BLR,19 deals from,"₹ 3,837",Select,None,None,IndiGo
3,"Flight option 5: Total cost ₹ 3,551.",07:30,HYD,1h 15,Direct,08:45,BLR,18 deals from,"₹ 3,551",Select,None,None,Vistara
4,"Flight option 6: Total cost ₹ 3,837.",20:30,HYD,1h 05,Direct,21:35,BLR,19 deals from,"₹ 3,837",Select,None,None,IndiGo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,"Flight option 80: Total cost ₹ 15,488.",20:30,HYD,19h 50,2 stops,"DEL, GAU",16:20+1,BLR,1 deal,"₹ 15,488",Select,None,Vistara
79,"Flight option 81: Total cost ₹ 13,183.",20:30,HYD,25h 20,2 stops,"DEL, IDR",21:50+1,BLR,1 deal,"₹ 13,183",Select,None,Hahn Air Systems
80,"Flight option 82: Total cost ₹ 35,437.",06:10,HYD,16h 20,1 stop,DEL,22:30,BLR,Operated by SpiceJet,4 deals from,"₹ 35,437",Select,Hahn Air Systems
81,"Flight option 83: Total cost ₹ 55,033.",19:10,HYD,13h 45,2 stops,"GOI, DEL",08:55+1,BLR,Operated by SpiceJet,1 deal,"₹ 55,033",Select,Hahn Air Systems
82,"Flight option 84: Total cost ₹ 50,927.",06:10,HYD,17h 15,2 stops,"DEL, GOI",23:25,BLR,Operated by SpiceJet,4 deals from,"₹ 50,927",Select,Hahn Air Systems

In [81]:
driver=webdriver.Chrome(r'C:\Users\surendar.reddy\Documents\data Science projet_Data traine\chromedriver.exe')
time.sleep(2)
url ="https://www.skyscanner.co.in/transport/flights/hyd/blr/220907/?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&priceSourceId=&priceTrace=&qp_prevCurrency=INR&qp_prevPrice=OneWayNone&qp_prevProvider=ins_month&rtn=0"
driver.get(url)

In [82]:
HYD_BAN_7Sep = []
HYD_BAN_7Sep_AIRLINES = []
for i in driver.find_elements_by_xpath('//div[@class="FlightsTicket_container__NWJkY"]'):
     HYD_BAN_7Sep.append(i.text.split('\n'))       
for i in driver.find_elements_by_xpath("//div[@class='BpkImage_bpk-image__NzYwO BpkImage_bpk-image--no-background__OTRiM']//img") :
     HYD_BAN_7Sep_AIRLINES.append(i.get_attribute('alt'))

# slicing odd
HYD_BAN_7Sep_AIRLINES  = HYD_BAN_7Sep_AIRLINES[::2]

#changing to dataframe
df_HYD_BAN_7Sep=pd.DataFrame(HYD_BAN_7Sep)
df_HYD_BAN_7Sep_AIRLINES=pd.DataFrame(HYD_BAN_7Sep_AIRLINES)

#join the 2 data Frame
df_HYD_BAN_7Sep = df_HYD_BAN_7Sep.join(df_HYD_BAN_7Sep_AIRLINES,how = 'right', lsuffix='_x')
#merged = df_train_csv.join(df_train_fly, how = 'right', lsuffix='_x')

#writing in Excel
writer=pd.ExcelWriter("df_HYD_BAN_7Sep.xlsx")
df_HYD_BAN_7Sep.to_excel(writer,"sheet", header=True, index= False)
writer.save()

#display the dataframe
df_HYD_BAN_7Sep

,0_x,1,2,3,4,5,6,7,8,9,10,11,0
0,"Flight option 1: Total cost ₹ 3,551.",18:25,HYD,1h 05,Direct,19:30,BLR,18 deals from,"₹ 3,551",Select,None,None,Vistara
1,"Flight option 2: Total cost ₹ 3,532.",06:00,HYD,1h 05,Direct,07:05,BLR,14 deals from,"₹ 3,532",Select,None,None,GoAir
2,"Flight option 3: Total cost ₹ 3,837.",09:30,HYD,1h 05,Direct,10:35,BLR,19 deals from,"₹ 3,837",Select,None,None,IndiGo
3,"Flight option 5: Total cost ₹ 3,551.",07:30,HYD,1h 15,Direct,08:45,BLR,18 deals from,"₹ 3,551",Select,None,None,Vistara
4,"Flight option 6: Total cost ₹ 3,681.",12:00,HYD,1h 15,Direct,13:15,BLR,15 deals from,"₹ 3,681",Select,None,None,Air India
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,"Flight option 90: Total cost ₹ 35,425.",06:15,HYD,13h 10,1 stop,JLR,19:25,BLR,Operated by SpiceJet,4 deals from,"₹ 35,425",Select,Hahn Air Systems
73,"Flight option 91: Total cost ₹ 36,258.",06:10,HYD,16h 20,1 stop,DEL,22:30,BLR,2 deals from,"₹ 36,258",Select,None,Hahn Air Systems
74,"Flight option 92: Total cost ₹ 55,033.",19:10,HYD,13h 45,2 stops,"GOI, DEL",08:55+1,BLR,Operated by SpiceJet,1 deal,"₹ 55,033",Select,Hahn Air Systems
75,"Flight option 93: Total cost ₹ 51,474.",06:10,HYD,17h 15,2 stops,"DEL, GOI",23:25,BLR,Partly operated by SpiceJet,2 deals from,"₹ 51,474",Select,Hahn Air Systems
76,"Flight option 94: Total cost ₹ 55,033.",06:00,HYD,16h 30,2 stops,"GOI, DEL",22:30,BLR,Partly operated by SpiceJet,1 deal,"₹ 55,033",Select,Hahn Air Systems